# Lot 6 : minéraux célèbres dans le monde de la minéralogie mais encore absents du référentiel (tellurures, halogénures de plomb-cuivre,
# carbonates et sulfates rares, phosphates de pegmatites, silicates de collection, gemmes rares, minéraux de météorites, minéraloïdes).
# Génère tools/minerals/lot6.json et la migration supabase/migrations/20261005200000_minerals_lot6.sql. Usage : python3 tools/minerals/lot6.py
import json, os
CL = {"E":"Éléments natifs","S":"Sulfures et sulfosels","H":"Halogénures","O":"Oxydes et hydroxydes","C":"Carbonates","U":"Sulfates, chromates, molybdates et tungstates","P":"Phosphates, arséniates et vanadates","B":"Borates",
      "N":"Silicates (nésosilicates)","So":"Silicates (sorosilicates)","Cy":"Silicates (cyclosilicates)","I":"Silicates (inosilicates)","Ph":"Silicates (phyllosilicates)","T":"Silicates (tectosilicates)"}
OUT = []
def M(name, slug, formula, system, cls, h, d, colors, luster, cleavage, streak, transp, fracture, habit, formation, etymology, confusions, description, fluo=None, var=None, rar="rare", grp=None, isgrp=False):
    OUT.append(dict(name=name, slug=slug, formula=formula, crystal_system=system, chemical_class=CL[cls], rarity=rar, hardness=h[0], hardness_max=h[1], density=d[0], density_max=d[1], colors=colors, luster=luster, cleavage=cleavage,
        streak=streak, transparency=transp, fracture=fracture, fluorescence=fluo, habit=habit, formation=formation, etymology=etymology, varieties=var, confusions=confusions, description=description, mineral_group=grp, is_group=isgrp))
RAD = " Radioactif : à conserver à l'écart, en boîte fermée."
# ---------- Météorites et éléments natifs ----------
M("Kamacite","kamacite","(Fe,Ni)","Cubique","E",(4,4),(7.9,8.2),["gris acier","argenté"],"métallique","aucun","gris","opaque","crochue","Lamelles dans les météorites ferreuses.","Météorites ferreuses (octaédrites) ; très rare sur Terre.","Du grec kamax (perche, barre), pour ses lamelles en barres.","Taénite : plus riche en nickel, plus claire.","Alliage naturel de fer et de nickel (5 à 7 % de nickel) des météorites ferreuses. Associé à la taénite, il dessine les figures de Widmanstätten que révèle une attaque à l'acide.")
M("Taénite","taenite","(Fe,Ni)","Cubique","E",(5,5.5),(7.8,8.2),["gris argenté","blanc d'acier"],"métallique","aucun","gris","opaque","crochue","Fins rubans entre les lamelles de kamacite.","Météorites ferreuses.","Du grec tainia (ruban), pour ses fins rubans.","Kamacite : moins riche en nickel, plus terne.","Alliage fer-nickel riche en nickel (de 25 à 65 %) qui dessine, autour de la kamacite, les rubans brillants des figures de Widmanstätten.")
M("Troilite","troilite","FeS","Hexagonal","S",(3.5,4),(4.6,4.8),["bronze","brun bronze"],"métallique","aucun","gris noir","opaque","irrégulière","Nodules et grains dans les météorites ferreuses.","Météorites (fer et chondrites), roches lunaires ; très rare sur Terre.","De Domenico Troili (1722-1792), qui décrivit en 1766 la météorite d'Albareto.","Pyrrhotite : moins pure, souvent magnétique.","Sulfure de fer pur, présent dans presque toutes les météorites et jusque dans les roches lunaires.")
M("Schreibersite","schreibersite","(Fe,Ni)₃P","Quadratique","E",(6.5,6.5),(7.0,7.3),["argenté à jaune bronze"],"métallique","parfait","gris noir","opaque","irrégulière","Lames et baguettes dans les météorites ferreuses.","Météorites ferreuses.","De Carl von Schreibers (1775-1852), directeur du cabinet impérial d'histoire naturelle de Vienne.","Kamacite : plus tendre.","Phosphure de fer et de nickel des météorites, qui fournit aux planétologues l'une des sources possibles de phosphore de la Terre primitive.")
M("Lonsdaléite","lonsdaleite","C","Hexagonal","E",(7,8),(3.2,3.3),["brun jaune","incolore"],"adamantin","aucun","blanc","translucide","irrégulière","Agrégats microscopiques.","Cratères d'impact et météorites à diamants (Canyon Diablo, Popigaï).","De Kathleen Lonsdale (1903-1971), cristallographe britannique.","Diamant : cubique.","Variante hexagonale du carbone, formée par le choc d'une météorite sur du graphite. Elle n'existe qu'en cristaux microscopiques.",rar="tres_rare")
# ---------- Tellurures et sulfosels ----------
M("Sylvanite","sylvanite","(Au,Ag)₂Te₄","Monoclinique","S",(1.5,2),(8.0,8.2),["blanc d'argent","jaune pâle"],"métallique","parfait","gris","opaque","irrégulière","Cristaux lamellaires en « écriture », masses.","Filons hydrothermaux d'or-tellure (Cripple Creek, Colorado ; Kalgoorlie ; Săcărâmb, Roumanie).","De la Transylvanie, d'où provenaient les premiers échantillons.","Calavérite : plus jaune, sans argent notable. Or natif : malléable.","Tellurure d'or et d'argent, minerai d'or de certains gisements. Il s'altère en laissant des pellicules d'or.")
M("Calavérite","calaverite","AuTe₂","Monoclinique","S",(2.5,3),(9.1,9.3),["jaune laiton","blanc argenté"],"métallique","aucun","gris verdâtre","opaque","subconchoïdale","Cristaux striés, masses grenues.","Filons hydrothermaux de basse température (Cripple Creek, Kalgoorlie, Calaveras County).","Du comté de Calaveras (Californie).","Or natif : malléable, plus jaune. Pyrite : plus dure, moins dense.","Tellurure d'or, le plus courant des tellurures d'or, avec environ 40 % d'or. Il est à l'origine de la ruée vers l'or de Cripple Creek et de Kalgoorlie.")
M("Hessite","hessite","Ag₂Te","Monoclinique","S",(2.5,3),(8.2,8.4),["gris acier","gris plomb"],"métallique","aucun","gris noir","opaque","subconchoïdale","Masses, rares cristaux pseudo-cubiques.","Filons hydrothermaux riches en tellure (Roumanie, Colorado, Altaï).","De Germain Henri Hess (1802-1850), chimiste suisse-russe.","Argentite : se coupe au couteau, sans tellure.","Tellurure d'argent tendre, qui se coupe au couteau et accompagne souvent l'or.")
M("Pétzite","petzite","Ag₃AuTe₂","Cubique","S",(2.5,3),(8.7,9.4),["gris acier","noir de fer"],"métallique","aucun","gris noir","opaque","subconchoïdale","Masses grenues, rares cristaux.","Filons hydrothermaux d'or-tellure (Cripple Creek, Kalgoorlie, Roumanie).","De W. Petz, qui l'analysa en 1845.","Hessite : sans or.","Tellurure d'or et d'argent gris acier, minerai d'or.",rar="tres_rare")
M("Siegénite","siegenite","(Ni,Co)₃S₄","Cubique","S",(4.5,5.5),(4.5,4.8),["gris acier","rose argenté"],"métallique","indistinct","gris noir","opaque","irrégulière","Octaèdres et masses grenues.","Filons hydrothermaux à nickel et cobalt (Siegerland, Katanga).","De Siegen (Allemagne).","Linnaéite : sans nickel notable. Pyrite : jaune, plus dure.","Sulfure de nickel et de cobalt, minerai de nickel de la région de Siegen.")
M("Greigite","greigite","Fe₃S₄","Cubique","S",(4,4),(4.0,4.1),["gris acier","violet sombre"],"métallique","indistinct","noir","opaque","irrégulière","Agrégats microscopiques.","Sédiments lacustres et marins pauvres en oxygène.","De Joseph W. Greig (1895-1977), minéralogiste américain.","Pyrite : jaune, non magnétique.","Sulfure de fer magnétique, produit par des bactéries qui s'orientent d'après le champ magnétique terrestre.")
M("Andorite","andorite","PbAgSb₃S₆","Orthorhombique","S",(3,3.5),(5.3,5.4),["gris d'acier","noir de fer"],"métallique","aucun","noir rougeâtre","opaque","subconchoïdale","Cristaux tabulaires, masses.","Filons à argent d'Oruro et de Potosí (Bolivie), Hongrie.","D'Andor von Semsey (1833-1923), minéralogiste hongrois.","Stéphanite : prismes plus courts.","Sulfosel de plomb, argent et antimoine, minerai d'argent des filons de Bolivie.")
M("Diaphorite","diaphorite","Pb₂Ag₃Sb₃S₈","Monoclinique","S",(2.5,3),(5.9,6.0),["gris acier","gris plomb"],"métallique","aucun","gris noir","opaque","irrégulière","Prismes striés, masses.","Filons à argent (Příbram, Bolivie, Idaho).","Du grec diaphora (différence), car elle diffère d'un minéral voisin, la freislébénite.","Pyrargyrite : trait rouge.","Sulfosel d'argent, de plomb et d'antimoine, minerai d'argent.")
M("Pearcéite","pearceite","(Ag,Cu)₁₆As₂S₁₁","Monoclinique","S",(3,3),(6.1,6.2),["noir de fer"],"métallique","aucun","noir","opaque","irrégulière","Tablettes hexagonales, masses.","Filons à argent (Colorado, Mexique, Chili).","De Richard Pearce (1837-1927), métallurgiste né en Cornouailles.","Polybasite : avec antimoine.","Sulfosel d'argent et d'arsenic, version arséniée de la polybasite.",rar="tres_rare")
M("Plagionite","plagionite","Pb₅Sb₈S₁₇","Monoclinique","S",(2.5,2.5),(5.4,5.5),["gris plomb","noir"],"métallique","parfait","gris noir","opaque","conchoïdale","Cristaux tabulaires, masses grenues.","Filons à plomb-antimoine (Wolfsberg, Harz).","Du grec plagios (oblique), pour ses cristaux obliques.","Boulangérite : fibreuse.","Sulfosel de plomb et d'antimoine, en tablettes obliques.",rar="tres_rare")
M("Livingstonite","livingstonite","HgSb₄S₈","Monoclinique","S",(2,2),(4.9,5.0),["gris plomb","rouge"],"métallique","parfait","rouge","opaque","irrégulière","Cristaux aciculaires et lamelles.","Gisements de mercure et d'antimoine (Huitzuco, Mexique).","De David Livingstone (1813-1873), explorateur écossais.","Stibine : sans mercure, trait gris. Cinabre : rouge vif.","Sulfure de mercure et d'antimoine, décrit à partir de la mine de Huitzuco au Mexique. Toxique : se laver les mains après manipulation.",rar="tres_rare")
M("Lorandite","lorandite","TlAsS₂","Monoclinique","S",(2,2.5),(5.5,5.6),["rouge cochenille","rouge sombre"],"adamantin","parfait","rouge cerise","translucide","irrégulière","Cristaux tabulaires, masses.","Gisement d'Allchar (Macédoine du Nord).","De Loránd Eötvös (1848-1919), physicien hongrois.","Réalgar : sans thallium.","Sulfosel de thallium et d'arsenic, spécialité d'Allchar, qui contient du thallium. Toxique : se laver les mains après manipulation.",rar="tres_rare")
# ---------- Halogénures ----------
M("Boléite","boleite","KPb₂₆Ag₉Cu₂₄(OH)₄₈Cl₆₂","Cubique","H",(3,3.5),(5.0,5.1),["bleu indigo","bleu foncé"],"vitreux nacré","parfait","bleu verdâtre","translucide","irrégulière","Cubes parfaits, souvent maclés avec la cumengéite.","Zone d'oxydation de gisements de cuivre-plomb-argent (Santa Rosalía, Boleo, Baja California).","De Boleo (Basse-Californie), la localité type.","Azurite : carbonate, effervescente. Cumengéite : quadratique.","Chlorure de plomb, de cuivre et d'argent d'un bleu indigo intense, en cubes parfaits parfois accolés à la cumengéite. Très recherché des collectionneurs.",rar="tres_rare")
M("Cumengéite","cumengeite","Pb₂₁Cu₂₀Cl₄₂(OH)₄₀","Quadratique","H",(2.5,2.5),(4.7,4.8),["bleu azur","bleu foncé"],"adamantin à vitreux","parfait","bleu clair","translucide","irrégulière","Cristaux tabulaires, souvent en épitaxie sur la boléite.","Zone d'oxydation de gisements de cuivre-plomb (Boleo, Baja California).","D'Édouard Cumenge (1828-1902), ingénieur des mines français, qui découvrit le gisement de Boléo.","Boléite : cubique, plus foncée.","Chlorure de plomb et de cuivre d'un bleu azur, formé de petits cristaux qui poussent sur les cubes de boléite.",rar="tres_rare")
# ---------- Oxydes ----------
M("Baddeleyite","baddeleyite","ZrO₂","Monoclinique","O",(6.5,6.5),(5.4,6.0),["brun","jaune brun","noir"],"submétallique à vitreux","parfait","blanc","translucide à opaque","irrégulière","Cristaux tabulaires, grains.","Carbonatites et roches basiques (Kovdor, Russie ; Sri Lanka ; Phalaborwa).","De Joseph Baddeley, alpiniste britannique qui rapporta les premiers échantillons de Ceylan en 1892.","Zircon : tétragonal, silicate.","Oxyde de zirconium naturel, rare, utilisé par les géologues pour dater certaines roches.",rar="tres_rare")
M("Hollandite","hollandite","Ba(Mn⁴⁺,Mn²⁺)₈O₁₆","Monoclinique","O",(6,6.5),(4.7,5.0),["gris argenté","noir"],"submétallique","bon","brun noir","opaque","irrégulière","Aiguilles, masses fibreuses.","Gisements de manganèse et zones d'oxydation (Inde, Afrique du Sud, Ghana).","De Thomas Holland (1868-1947), directeur du Geological Survey of India.","Cryptomélane : analyse nécessaire.","Oxyde de manganèse et de baryum à structure en tunnels, dédié à un géologue britannique de l'Inde.")
M("Hétérogénite","heterogenite","CoO(OH)","Trigonal","O",(3,4),(3.4,4.0),["noir","brun noir"],"submétallique à terne","parfait","brun noir","opaque","irrégulière","Masses botryoïdales et croûtes.","Zone d'oxydation des gisements de cuivre-cobalt (Katanga, RD Congo).","Du grec heterogenes (de nature différente), car sa composition étonna.","Pyrolusite : sans cobalt, trait noir.","Oxy-hydroxyde de cobalt noir, minerai de cobalt d'Afrique centrale.")
M("Tapiolite","tapiolite","(Fe,Mn)(Ta,Nb)₂O₆","Quadratique","O",(6,6.5),(7.9,8.2),["noir","brun noir"],"submétallique","indistinct","brun à noir","opaque","irrégulière","Cristaux courts, masses.","Pegmatites à lithium et tantale.","De Tapio, dieu finlandais des forêts.","Colombo-tantalite : orthorhombique.","Oxyde de tantale et de fer dense des pegmatites, quadratique alors que la tantalite est orthorhombique.")
M("Samarskite-(Y)","samarskite","(Y,Fe³⁺,U)(Nb,Ta)O₄","Monoclinique","O",(5,6),(5.4,5.9),["noir de velours","brun noir"],"résineux à submétallique","aucun","brun rouge","opaque","conchoïdale","Masses et cristaux grossiers.","Pegmatites granitiques (Caroline du Nord, Brésil, Madagascar).","De Vasili Samarsky-Bykhovets (1803-1870), ingénieur des mines russe.","Gadolinite : plus tendre.","Oxyde d'yttrium, de niobium et de tantale, qui a donné son nom au samarium. Souvent rendu amorphe par sa radioactivité."+RAD)
M("Fergusonite-(Y)","fergusonite","YNbO₄","Quadratique","O",(5.5,6.5),(4.3,5.8),["brun noir","noir"],"vitreux à submétallique","indistinct","brun clair","opaque","conchoïdale","Prismes à section carrée, masses.","Pegmatites granitiques (Norvège, Madagascar, Texas).","De Robert Ferguson of Raith (1767-1840), collectionneur écossais.","Samarskite : sans clivage net, monoclinique.","Niobate d'yttrium des pegmatites, source de terres rares."+RAD)
# ---------- Carbonates ----------
M("Ikaïte","ikaite","CaCO₃·6H₂O","Monoclinique","C",(3,3),(1.8,1.8),["incolore","blanc"],"vitreux","aucun","blanc","transparent","irrégulière","Colonnes et pointes de glace blanche.","Eaux froides (fjord d'Ikka, Groenland) ; sédiments polaires.","De l'Ikka Fjord (Groenland), où elle forme des colonnes sous-marines.","Gypse : plus stable.","Carbonate de calcium hydraté qui n'existe qu'à basse température : elle se décompose en calcite quand elle se réchauffe.",rar="tres_rare")
M("Pirssonite","pirssonite","Na₂Ca(CO₃)₂·2H₂O","Orthorhombique","C",(3,3.5),(2.35,2.35),["incolore","blanc"],"vitreux","parfait","blanc","transparent à translucide","conchoïdale","Cristaux pyramidaux, croûtes.","Lacs salés (Searles Lake, Californie ; Green River, Wyoming).","De Louis Valentine Pirsson (1860-1919), pétrographe américain.","Gaylussite : plus tendre.","Carbonate double de sodium et de calcium des lacs salés alcalins.",rar="tres_rare")
M("Natron","natron","Na₂CO₃·10H₂O","Monoclinique","C",(1,1.5),(1.44,1.47),["incolore","blanc","jaunâtre"],"vitreux","parfait","blanc","transparent à translucide","conchoïdale","Croûtes et efflorescences.","Lacs salés alcalins (Wadi Natrun, Égypte ; lac Natron, Tanzanie).","De l'arabe natrun, via l'égyptien ancien.","Trona : moins hydraté.","Carbonate de sodium décahydraté, utilisé dès l'Antiquité égyptienne, notamment pour la momification. Il perd son eau à l'air.")
M("Artinite","artinite","Mg₂(CO₃)(OH)₂·3H₂O","Monoclinique","C",(2.5,2.5),(2.0,2.03),["blanc","incolore"],"soyeux à vitreux","parfait","blanc","transparent à translucide","irrégulière","Aiguilles et fibres en touffes rayonnantes.","Serpentinites altérées (Val Lanzo, Italie ; New York ; Californie).","D'Ettore Artini (1866-1928), minéralogiste italien.","Hydromagnésite : plus massive.","Carbonate hydraté de magnésium en gerbes d'aiguilles soyeuses sur les serpentinites.")
M("Ancylite-(Ce)","ancylite","SrCe(CO₃)₂(OH)·H₂O","Orthorhombique","C",(4,4.5),(3.9,4.0),["jaune brun","brun rouge"],"vitreux à gras","aucun","jaune pâle","translucide","irrégulière","Cristaux en octaèdres aplatis, croûtes.","Pegmatites et carbonatites alcalines (Mont Saint-Hilaire, Québec ; Narsarsuk).","Du grec ankylos (courbé), pour ses cristaux aux faces arquées.","Bastnäsite : hexagonal.","Carbonate de strontium et de cérium des roches alcalines.",rar="tres_rare")
M("Synchysite-(Ce)","synchysite","CaCe(CO₃)₂F","Monoclinique","C",(4.5,4.5),(3.9,4.0),["jaune miel","brun jaune"],"vitreux à résineux","aucun","blanc","translucide","irrégulière","Cristaux en fuseaux, souvent en intercroissance.","Pegmatites et carbonatites (Norvège, Malawi, Zagi, Pakistan).","Du grec synchysis (confusion), car on le confondait avec la parisite.","Parisite : voir sa fiche.","Fluocarbonate de calcium et de cérium, voisin de la bastnäsite et de la parisite.",rar="tres_rare")
M("Stichtite","stichtite","Mg₆Cr₂(CO₃)(OH)₁₆·4H₂O","Trigonal","C",(1.5,2),(2.16,2.2),["rose","lilas","violet"],"gras à nacré","parfait","blanc rosé","translucide","irrégulière","Masses lamellaires à écailles.","Serpentinites à chromite (Tasmanie, Afrique du Sud, Canada).","De Robert Sticht (1856-1922), directeur de la mine de Mount Lyell (Tasmanie).","Lépidolite : plus dure, en paillettes.","Carbonate de magnésium et de chrome, rose lilas, associé à la serpentine verte dans des pierres ornementales (« atlantisite »).")
# ---------- Sulfates et tungstates ----------
M("Syngénite","syngenite","K₂Ca(SO₄)₂·H₂O","Monoclinique","U",(2.5,2.5),(2.57,2.58),["incolore","blanc","jaunâtre"],"vitreux","parfait","blanc","transparent à translucide","conchoïdale","Cristaux tabulaires ou en prismes.","Évaporites potassiques (Kalusz, Ukraine ; Stassfurt, Allemagne).","Du grec syn (avec) et genesis (formation), pour son association avec d'autres sels.","Gypse : sans potassium, plus tendre.","Sulfate de potassium et de calcium des gisements de sels de potasse.")
M("Blödite","bloedite","Na₂Mg(SO₄)₂·4H₂O","Monoclinique","U",(2.5,3),(2.25,2.28),["incolore","vert pâle","rougeâtre"],"vitreux","aucun","blanc","transparent à translucide","conchoïdale","Cristaux courts, masses granuleuses.","Évaporites et lacs salés (Ischl, Autriche ; Searles Lake).","De Carl August Blöde (1773-1820), chimiste allemand.","Épsomite : plus soluble.","Sulfate double de sodium et de magnésium des dépôts salins.")
M("Langbeinite","langbeinite","K₂Mg₂(SO₄)₃","Cubique","U",(3.5,4),(2.82,2.83),["incolore","blanc","jaunâtre","rose"],"vitreux","aucun","blanc","transparent","conchoïdale","Cristaux tétraédriques, masses.","Évaporites de potasse (Carlsbad, Nouveau-Mexique ; Stassfurt).","D'Albert Langbein, chimiste allemand du XIXe siècle.","Sylvite : cubique, plus tendre.","Sulfate de potassium et de magnésium, exploité comme engrais.")
M("Spangolite","spangolite","Cu₆Al(SO₄)(OH)₁₂Cl·3H₂O","Trigonal","U",(2,3),(3.1,3.14),["vert profond","vert bleuté"],"vitreux","parfait","vert pâle","transparent à translucide","irrégulière","Petits cristaux hexagonaux en pyramides.","Zone d'oxydation de gisements de cuivre (Bisbee, Arizona).","De Norman Spang (XIXe siècle), collectionneur de Pennsylvanie.","Brochantite : sans aluminium ni chlore.","Chlorosulfate de cuivre et d'aluminium d'un vert intense, recherché pour ses petits cristaux géométriques.",rar="tres_rare")
M("Voltaïte","voltaite","K₂Fe²⁺₅Fe³⁺₃Al(SO₄)₁₂·18H₂O","Cubique","U",(3,3),(2.8,2.9),["noir verdâtre","vert foncé"],"vitreux à résineux","aucun","gris verdâtre","translucide à opaque","irrégulière","Octaèdres et cubo-octaèdres.","Fumerolles et zones d'oxydation de sulfures (Solfatara de Pouzzoles, Italie).","D'Alessandro Volta (1745-1827), physicien italien.","Tourmaline : plus dure.","Sulfate hydraté de potassium, fer et aluminium, en cristaux noirs brillants dédiés à l'inventeur de la pile.")
M("Szomolnokite","szomolnokite","FeSO₄·H₂O","Monoclinique","U",(2.5,2.5),(3.0,3.1),["jaune brun","blanc jaunâtre"],"vitreux","parfait","blanc","translucide","irrégulière","Croûtes et masses granuleuses.","Mines de sulfures oxydées (Smolník, Slovaquie ; Chili).","De Szomolnok (aujourd'hui Smolník, Slovaquie).","Mélantérite : plus hydratée.","Sulfate de fer produit par l'oxydation de la pyrite dans les mines.")
M("Halotrichite","halotrichite","FeAl₂(SO₄)₄·22H₂O","Monoclinique","U",(1.5,2),(1.9,1.95),["incolore","jaunâtre","blanc"],"soyeux","aucun","blanc","transparent à translucide","irrégulière","Fibres soyeuses, efflorescences.","Schistes pyriteux altérés, fumerolles.","Du grec hals (sel) et thrix (cheveu).","Pickeringite : sans fer.","Sulfate hydraté de fer et d'aluminium en fibres soyeuses.")
M("Raspite","raspite","PbWO₄","Monoclinique","U",(2.5,3),(8.5,8.5),["jaune brun","jaune","blanc"],"adamantin","parfait","blanc","translucide","irrégulière","Cristaux tabulaires.","Zone d'oxydation des gisements de plomb (Broken Hill, Australie).","De Charles Rasp (1846-1907), découvreur du gisement de Broken Hill.","Stolzite : quadratique.","Tungstate de plomb monoclinique, dimorphe de la stolzite.",rar="tres_rare")
# ---------- Phosphates et arséniates ----------
M("Scorzalite","scorzalite","(Fe,Mg)Al₂(PO₄)₂(OH)₂","Monoclinique","P",(5.5,6),(3.3,3.4),["bleu foncé","bleu azur"],"vitreux","bon","blanc bleuté","translucide","irrégulière","Cristaux trapus, masses.","Pegmatites (Minas Gerais, Yukon, Rwanda).","D'Evaristo Pena Scorza, minéralogiste brésilien.","Lazulite : plus riche en magnésium, plus claire.","Phosphate de fer et d'aluminium bleu foncé, pôle ferreux de la série de la lazulite.")
M("Struvite","struvite","(NH₄)MgPO₄·6H₂O","Orthorhombique","P",(1.5,2),(1.7,1.71),["incolore","jaune pâle","blanc"],"vitreux","bon","blanc","transparent à translucide","irrégulière","Cristaux hémimorphes, croûtes.","Guano, sols riches en matière organique, anciennes fosses ; calculs urinaires.","De Heinrich von Struve (1772-1851), diplomate et minéralogiste russe.","Brushite : monoclinique.","Phosphate d'ammonium et de magnésium qui cristallise dans les milieux riches en matière organique.")
M("Brushite","brushite","CaHPO₄·2H₂O","Monoclinique","P",(2.5,2.5),(2.3,2.33),["incolore","jaunâtre","blanc"],"vitreux à nacré","parfait","blanc","transparent à translucide","irrégulière","Cristaux prismatiques, croûtes.","Guano et grottes à phosphates (île d'Aves, Mona).","De George Jarvis Brush (1831-1912), minéralogiste américain de Yale.","Gypse : sans phosphore.","Phosphate de calcium hydraté des guanos, également présent dans certains calculs rénaux.")
M("Whitlockite","whitlockite","Ca₉Mg(PO₃OH)(PO₄)₆","Trigonal","P",(5,5),(3.1,3.2),["incolore","brun clair","rose"],"vitreux","aucun","blanc","transparent à translucide","irrégulière","Cristaux tabulaires, grains.","Pegmatites à phosphates, météorites et roches lunaires.","De Herbert Percy Whitlock (1868-1948), conservateur du Muséum américain d'histoire naturelle.","Apatite : hexagonal.","Phosphate de calcium et de magnésium des pegmatites, des météorites et des roches lunaires.")
M("Florencite-(Ce)","florencite","CeAl₃(PO₄)₂(OH)₆","Trigonal","P",(5,6),(3.5,3.7),["jaune","jaune brun","gris"],"vitreux à résineux","parfait","blanc","translucide","irrégulière","Petits cristaux rhomboédriques.","Gîtes de bauxite et altérations de roches alcalines (Minas Gerais, Brésil).","De William Florence, chimiste brésilien.","Goyazite : plus riche en strontium.","Phosphate d'aluminium et de cérium du groupe de la crandallite, source de terres rares.",rar="tres_rare")
M("Herderite","herderite","CaBe(PO₄)F","Monoclinique","P",(5,5.5),(2.95,3.03),["incolore","jaune pâle","vert pâle","violet"],"vitreux","imparfait","blanc","transparent à translucide","conchoïdale","Cristaux prismatiques striés.","Pegmatites (Maine, Minas Gerais, Pakistan).","De Siegmund August Wolfgang von Herder (1776-1838), directeur des mines de Saxe.","Apatite : plus tendre, sans béryllium.","Phosphate de calcium et de béryllium, parfois taillé en gemme de collection.",rar="tres_rare")
M("Béryllonite","beryllonite","NaBePO₄","Monoclinique","P",(5.5,6),(2.8,2.85),["incolore","blanc","jaune pâle"],"vitreux à nacré","parfait","blanc","transparent","conchoïdale","Cristaux tabulaires ou prismatiques.","Pegmatites (Stoneham, Maine ; Minas Gerais).","De sa composition : béryllium et sodium.","Quartz : sans clivage.","Phosphate de sodium et de béryllium, parfois taillé en gemme incolore.",rar="tres_rare")
M("Liroconite","liroconite","Cu₂Al(AsO₄)(OH)₄·4H₂O","Monoclinique","P",(2,2.5),(2.9,3.0),["bleu","bleu vert","vert"],"vitreux à résineux","imparfait","bleu pâle","transparent à translucide","conchoïdale","Cristaux lenticulaires en « pastilles ».","Zone d'oxydation de gisements de cuivre (Cornouailles, notamment Wheal Gorland).","Du grec leiros (pâle) et konia (poudre).","Azurite : carbonate, effervescente.","Arséniate de cuivre et d'aluminium bleu, en cristaux en lentilles typiques des vieilles mines de Cornouailles."+" Toxique : se laver les mains après manipulation.",rar="tres_rare")
# ---------- Silicates ----------
M("Scapolite","scapolite","(Na,Ca)₄[(Al,Si)₃Si₉O₂₄](Cl,CO₃,SO₄)","Quadratique","T",(5.5,6),(2.5,2.8),["incolore","jaune","rose","violet","bleu","gris"],"vitreux","bon","blanc","transparent à translucide","conchoïdale à irrégulière","Prismes à section carrée, masses.","Roches métamorphiques calcaires, marbres et skarns, gneiss.","Du grec skapos (bâton), pour ses cristaux en prismes.","Feldspath : clivages à 90° nets, système différent. Béryl : hexagonal.","Série entre la marialite (sodique) et la méionite (calcique), dont certaines variétés jaunes ou violettes sont taillées en gemmes.",fluo="Souvent jaune ou rose sous UV longs.",var="Marialite (pôle sodique) ; méionite (pôle calcique).",isgrp=True)
M("Astrophyllite","astrophyllite","K₂NaFe²⁺₇Ti₂(Si₄O₁₂)₂O₂(OH)₄F","Triclinique","Ph",(3,3.5),(3.3,3.4),["jaune bronze","brun doré"],"nacré à vitreux","parfait","brun jaune","translucide à opaque","irrégulière","Lames en gerbes étoilées.","Syénites et pegmatites alcalines (Kola, Mont Saint-Hilaire, Pikes Peak).","Du grec astron (étoile) et phyllon (feuille), pour ses lames en gerbes étoilées.","Biotite : plus noire, élastique.","Silicate de potassium, sodium, fer et titane en gerbes de lames dorées sur des roches alcalines.")
M("Neptunite","neptunite","KNa₂Li(Fe²⁺,Mn²⁺)₂Ti₂Si₈O₂₄","Monoclinique","I",(5,6),(3.19,3.23),["noir","brun rouge"],"vitreux","parfait","brun rouge","translucide en lame mince","conchoïdale","Prismes allongés à section carrée.","Dans les roches à benitoite (San Benito, Californie) ; Groenland.","De Neptune, dieu romain de la mer, car on le trouva avec l'aegyrine, du nom du dieu nordique Ægir.","Aegyrine : plus vert, plus tendre. Tourmaline noire : section triangulaire.","Silicate de potassium, sodium, lithium, fer et titane, noir brillant, qui accompagne la benitoite en Californie.")
M("Gadolinite-(Y)","gadolinite","Y₂Fe²⁺Be₂Si₂O₁₀","Monoclinique","N",(6.5,7),(4.0,4.7),["noir verdâtre","brun noir"],"vitreux à gras","aucun","gris vert","opaque","conchoïdale","Cristaux prismatiques, masses.","Pegmatites granitiques (Ytterby, Suède ; Norvège ; Texas).","De Johan Gadolin (1760-1852), chimiste finlandais qui isola l'oxyde d'yttrium.","Tourmaline noire : trigonal, plus claire.","Silicate d'yttrium, de fer et de béryllium d'Ytterby, source de plusieurs terres rares."+RAD)
M("Épididymite","epididymite","NaBeSi₃O₇(OH)","Orthorhombique","Ph",(5.5,5.5),(2.55,2.58),["blanc","incolore"],"vitreux à nacré","parfait","blanc","transparent à translucide","irrégulière","Cristaux tabulaires maclés, rosettes.","Pegmatites alcalines (Mont Saint-Hilaire, Narsarsuk, Norvège).","Du grec epididymos (jumeau), pour ses macles fréquentes.","Eudidymite : monoclinique.","Silicate de sodium et de béryllium en cristaux souvent maclés en rosettes.",rar="tres_rare")
M("Humite","humite","(Mg,Fe)₇(SiO₄)₃(F,OH)₂","Orthorhombique","N",(6,6.5),(3.1,3.2),["jaune","orange","brun"],"vitreux","médiocre","blanc","transparent à translucide","conchoïdale","Cristaux à nombreuses facettes.","Calcaires métamorphisés et skarns (Vésuve, Monte Somma).","De Sir Abraham Hume (1749-1838), collectionneur britannique.","Olivine : plus verte.","Silicate de magnésium à fluor du Vésuve, tête de file du groupe de la humite.",rar="tres_rare")
M("Chondrodite","chondrodite","(Mg,Fe)₅(SiO₄)₂(F,OH)₂","Monoclinique","N",(6,6.5),(3.1,3.2),["jaune","orange","rouge","brun"],"vitreux à résineux","médiocre","blanc","transparent à translucide","conchoïdale","Grains arrondis, cristaux trapus.","Calcaires cristallins, marbres et skarns (Tilly Foster, New York ; Suède).","Du grec chondros (grain), pour ses grains dans les marbres.","Humite : orthorhombique.","Silicate de magnésium à fluor, en grains jaune orangé dans les marbres.",rar="tres_rare")
M("Babingtonite","babingtonite","Ca₂Fe²⁺Fe³⁺Si₅O₁₄(OH)","Triclinique","I",(5.5,6),(3.3,3.4),["noir verdâtre","noir"],"vitreux","parfait","gris vert","opaque","conchoïdale","Cristaux tabulaires brillants.","Fentes alpines, cavités de basaltes et skarns (Arendal, Norvège ; Pakistan).","De William Babington (1756-1833), minéralogiste irlandais.","Épidote : plus verte. Augite : prismes à 87°.","Silicate de calcium et de fer en petits cristaux noirs brillants sur la prehnite.")
M("Inésite","inesite","Ca₂Mn₇Si₁₀O₂₈(OH)₂·5H₂O","Triclinique","I",(5.5,6),(3.0,3.05),["rose chair","rouge","brun rouge"],"vitreux à soyeux","parfait","blanc","translucide","irrégulière","Aiguilles en gerbes, masses fibreuses.","Gisements de manganèse (Hotazel, Afrique du Sud ; N'Chwaning).","Du grec is, inos (fibre).","Rhodonite : plus dure, rose plus vif.","Silicate de calcium et de manganèse en gerbes rose chair, typique des mines de manganèse d'Afrique du Sud.",rar="tres_rare")
M("Ajoïte","ajoite","(K,Na)₃Cu₂₀Al₃Si₂₉O₇₆(OH)₁₆·8H₂O","Triclinique","Ph",(3,4),(2.9,3.0),["bleu vert pâle","turquoise"],"vitreux à terne","aucun","blanc bleuté","translucide à opaque","irrégulière","Inclusions en fines aiguilles dans le quartz (« quartz ajoïte »), enduits.","Zone d'oxydation de gisements de cuivre (New Cornelia, Ajo, Arizona ; Messina, Afrique du Sud).","D'Ajo (Arizona).","Chrysocolle : plus terne, plus tendre.","Silicate de cuivre et d'aluminium d'un bleu vert pâle, surtout connu comme inclusions dans le quartz.",rar="tres_rare")
M("Tobermorite","tobermorite","Ca₅Si₆O₁₆(OH)₂·4H₂O","Orthorhombique","I",(2.5,2.5),(2.4,2.5),["blanc","blanc rosé"],"nacré à terne","parfait","blanc","translucide","irrégulière","Lames, masses fibreuses.","Skarns et cavités de basaltes ; composant du ciment romain.","De Tobermory, île de Mull (Écosse).","Xonotlite : plus dure.","Silicate de calcium hydraté, dont une forme se développe lentement dans le béton romain immergé et lui donne sa longévité.")
M("Xonotlite","xonotlite","Ca₆Si₆O₁₇(OH)₂","Monoclinique","I",(6.5,6.5),(2.7,2.7),["blanc","gris","rose"],"vitreux à soyeux","parfait","blanc","translucide à opaque","irrégulière","Fibres, masses compactes.","Skarns et roches calco-silicatées (Tetela de Xonotla, Mexique ; Californie).","De Tetela de Xonotla (Mexique).","Wollastonite : plus tendre.","Silicate de calcium fibreux, parfois sculpté en pierre ornementale rose.")
M("Hackmanite","hackmanite","Na₈(Al₆Si₆O₂₄)(Cl,S)₂","Cubique","T",(5.5,6),(2.2,2.4),["blanc rosé","violet","bleu vert"],"vitreux à gras","imparfait","blanc","transparent à translucide","conchoïdale","Masses, rares cristaux dodécaédriques.","Syénites néphéliniques (Mont Saint-Hilaire, Kola, Myanmar, Afghanistan).","De Victor Hackman (1866-1941), géologue finlandais.","Sodalite : sans ténébrescence marquée.","Variété de sodalite qui change de couleur à la lumière du soleil et retrouve sa teinte dans le noir.",fluo="Orange à rose vif sous UV longs.",rar="tres_rare")
M("Tourmaline Paraïba","tourmaline-paraiba","Na(Li,Al)₃Al₆(BO₃)₃Si₆O₁₈(OH)₄ (avec Cu)","Trigonal","Cy",(7,7.5),(3.0,3.1),["bleu néon","bleu turquoise","vert","violet"],"vitreux","aucun","blanc","transparent","conchoïdale","Prismes striés, souvent taillés.","Pegmatites (Paraíba et Rio Grande do Norte, Brésil ; Nigeria ; Mozambique).","De l'État de Paraíba (Brésil), où elle fut découverte à la fin des années 1980.","Apatite bleue : plus tendre. Topaze bleue : sans pléochroïsme marqué.","Variété d'elbaïte colorée par le cuivre, d'un bleu néon unique ; l'une des gemmes les plus chères du monde.",rar="tres_rare",grp="tourmaline")
M("Achroïte","achroite","Na(Li,Al)₃Al₆(BO₃)₃Si₆O₁₈(OH)₄","Trigonal","Cy",(7,7.5),(3.0,3.1),["incolore"],"vitreux","aucun","blanc","transparent","conchoïdale","Prismes striés incolores.","Pegmatites à lithium (Elbe, Brésil, Madagascar).","Du grec achroos (sans couleur).","Quartz : sans stries.","Variété incolore d'elbaïte, assez rare, souvent en prismes terminés de cristaux colorés.",rar="tres_rare",grp="tourmaline")
M("Diopside chromifère","diopside-chromifere","CaMgSi₂O₆ (avec Cr)","Monoclinique","I",(5.5,6.5),(3.2,3.4),["vert émeraude","vert foncé"],"vitreux","bon, à 87° et 93°","blanc à gris verdâtre","transparent à translucide","conchoïdale à inégale","Prismes courts, grains.","Kimberlites et roches basiques riches en chrome (Sibérie, Finlande).","Du diopside (du grec di- et opsis, double vue) et du chrome qui le colore.","Émeraude : plus dure. Tourmaline verte : plus dure.","Variété verte de diopside colorée par le chrome, taillée en gemme de petite taille.",rar="rare",grp="pyroxene")
M("Thortveitite","thortveitite","Sc₂Si₂O₇","Monoclinique","So",(6,7),(3.57,3.6),["vert gris","brun","noir verdâtre"],"vitreux","parfait","blanc","translucide","conchoïdale","Cristaux prismatiques allongés, parfois en rayonnement.","Pegmatites (Iveland, Norvège ; Madagascar).","D'Olaus Thortveit (1877-1961), minéralogiste norvégien.","Béryl : hexagonal.","Principal minéral du scandium, très rare, trouvé en Norvège et à Madagascar.",rar="tres_rare")
M("Eucryptite","eucryptite","LiAlSiO₄","Trigonal","N",(6.5,6.5),(2.67,2.7),["incolore","blanc","gris"],"vitreux","aucun","blanc","transparent à translucide","irrégulière","Masses, intercroissance avec l'albite.","Pegmatites à lithium (Branchville, Connecticut ; Bikita, Zimbabwe).","Du grec eu (bien) et kryptos (caché), car il se cache dans l'albite.","Quartz : plus dur.","Aluminosilicate de lithium, exploité avec la pétalite et le spodumène comme minerai de lithium.",rar="tres_rare")
M("Arfvedsonite","arfvedsonite","Na₃(Fe²⁺₄Fe³⁺)Si₈O₂₂(OH)₂","Monoclinique","I",(5.5,6),(3.4,3.5),["noir","vert noir"],"vitreux","parfait, à 56° et 124°","bleu gris","opaque","irrégulière","Cristaux prismatiques allongés, masses.","Syénites et granites alcalins (Groenland, Kola, Mont Saint-Hilaire).","De Johan August Arfwedson (1792-1841), chimiste suédois qui découvrit le lithium.","Hornblende : moins sodique.","Amphibole sodique noire des roches alcalines, dédiée au découvreur du lithium.",grp="amphibole")
M("Clinoptilolite","clinoptilolite","(Na,K,Ca)₂₋₃Al₃(Al,Si)₂Si₁₃O₃₆·12H₂O","Monoclinique","T",(3.5,4),(2.1,2.2),["blanc","rose","incolore"],"vitreux à nacré","parfait","blanc","transparent à translucide","irrégulière","Cristaux tabulaires, masses terreuses.","Cendres volcaniques altérées, lacs salés.","Du grec klino (oblique) et ptilon (plume).","Heulandite : voir sa fiche.","Zéolite très répandue des cendres volcaniques altérées, exploitée comme filtre et adsorbant.",grp="zeolite")
M("Lévyne","levyne","(Ca,Na₂,K₂)₃[Al₆Si₁₂O₃₆]·18H₂O","Trigonal","T",(4,4.5),(2.1,2.2),["blanc","incolore","rose pâle"],"vitreux","imparfait","blanc","transparent à translucide","irrégulière","Cristaux en disques, souvent maclés.","Cavités de basaltes (Islande, Écosse, îles Féroé, Antrim).","D'Armand Lévy (1795-1841), minéralogiste français.","Chabazite : rhomboèdres plus nets.","Zéolite en petits disques ou rhomboèdres tabulaires des cavités de basaltes.",grp="zeolite",rar="tres_rare")
M("Épistilbite","epistilbite","CaAl₂Si₆O₁₆·5H₂O","Monoclinique","T",(4,4.5),(2.2,2.4),["blanc","rose","incolore"],"vitreux à nacré","parfait","blanc","transparent à translucide","irrégulière","Cristaux maclés en sphères et lames.","Cavités de basaltes (Berufjördur, Islande ; Nasik, Inde).","Du grec epi (sur) et de la stilbite, car il croît sur la stilbite.","Stilbite : gerbes différentes.","Zéolite en cristaux maclés, qui recouvre souvent la stilbite dans les basaltes.",grp="zeolite",rar="tres_rare")
M("Edingtonite","edingtonite","BaAl₂Si₃O₁₀·4H₂O","Orthorhombique","T",(4,4.5),(2.7,2.8),["incolore","blanc","gris","rose pâle"],"vitreux","parfait","blanc","transparent à translucide","irrégulière","Petits cristaux en pyramides, croûtes.","Cavités de basaltes et roches alcalines (Kilpatrick Hills, Écosse ; Böhlet, Suède).","De James Edington, minéralogiste écossais, qui le trouva en 1823.","Harmotome : maclé en croix.","Zéolite barytique rare, décrite en Écosse.",grp="zeolite",rar="tres_rare")
M("Hardystonite","hardystonite","Ca₂ZnSi₂O₇","Quadratique","So",(3,4),(3.4,3.5),["blanc","gris","incolore"],"vitreux","parfait","blanc","translucide","conchoïdale","Masses grenues.","Gisements de zinc de Franklin et Ogdensburg (New Jersey).","De Hardyston (New Jersey), où l'espèce fut décrite.","Wollastonite : fibreuse.","Silicate de calcium et de zinc, célèbre pour sa fluorescence violette dans les roches fluorescentes de Franklin.",fluo="Violet à bleu sous UV courts, souvent à côté de la willémite verte.",rar="tres_rare")
M("Pyroxmangite","pyroxmangite","(Mn,Fe)SiO₃","Triclinique","I",(5.5,6),(3.6,3.8),["rose","brun rose","rouge brun"],"vitreux à nacré","parfait","blanc","transparent à translucide","irrégulière","Cristaux tabulaires, masses.","Gisements de manganèse métamorphisés, skarns (Broken Hill, Japon).","Du pyroxène et du manganèse, deux éléments de sa nature.","Rhodonite : voir sa fiche.","Silicate de manganèse rose, proche de la rhodonite mais de structure différente.",grp="pyroxene",rar="tres_rare")
M("Anorthoclase","anorthoclase","(Na,K)AlSi₃O₈","Triclinique","T",(6,6),(2.58,2.6),["incolore","blanc","jaune pâle"],"vitreux","parfait","blanc","transparent à translucide","conchoïdale","Cristaux tabulaires maclés.","Roches volcaniques sodiques (Kenya, mont Erebus, Antarctique).","Du grec an- (non), orthos (droit) et klasis (cassure), car ses clivages ne sont pas à angle droit.","Sanidine : voir sa fiche.","Feldspath alcalin riche en sodium des laves, dont les cristaux se trouvent sur le mont Erebus.",grp="feldspath",rar="tres_rare")
M("Hyalophane","hyalophane","(K,Ba)Al(Si,Al)₃O₈","Monoclinique","T",(6,6.5),(2.8,2.9),["incolore","blanc","jaune pâle"],"vitreux","parfait","blanc","transparent à translucide","conchoïdale","Cristaux prismatiques.","Gisements métamorphisés riches en manganèse (Binn, Valais ; Broken Hill).","Du grec hyalos (verre) et phainesthai (apparaître), pour son aspect vitreux.","Orthose : sans baryum, moins dense.","Feldspath barytique, à éclat vitreux, de série avec la celsiane.",grp="feldspath",rar="tres_rare")
M("Celsiane","celsian","BaAl₂Si₂O₈","Monoclinique","T",(6,6.5),(3.1,3.4),["incolore","blanc","jaunâtre"],"vitreux","parfait","blanc","transparent à translucide","irrégulière","Cristaux prismatiques et masses.","Gisements métamorphiques riches en manganèse et baryum (Broken Hill, Suède, Valais).","D'Anders Celsius (1701-1744), astronome et physicien suédois.","Feldspath ordinaire : moins dense.","Feldspath barytique dédié au créateur de l'échelle de température Celsius.",grp="feldspath",rar="tres_rare")
M("Paragonite","paragonite","NaAl₂(AlSi₃O₁₀)(OH)₂","Monoclinique","Ph",(2.5,3),(2.85,2.9),["blanc","jaune pâle","verdâtre"],"nacré","parfait","blanc","translucide","irrégulière","Lamelles et masses écailleuses.","Schistes métamorphiques de haute pression, notamment bleus.","Du grec paragein (induire en erreur), car il fut pris pour du talc.","Muscovite : potassique, difficile à distinguer sans analyse.","Mica blanc sodique des schistes de haute pression, difficile à distinguer de la muscovite.",grp="mica")
M("Serendibite","serendibite","Ca₂(Mg,Al)₆(Si,Al,B)₆O₂₀","Triclinique","B",(6.5,7),(3.42,3.52),["bleu foncé","gris bleuté","vert"],"vitreux","aucun","blanc","transparent à translucide","conchoïdale","Grains et cristaux massifs.","Skarns de Ceylan (Sri Lanka) ; Mogok (Birmanie).","De Serendib, ancien nom arabe du Sri Lanka.","Saphir : plus dur, sans bore.","Borosilicate de calcium, magnésium et aluminium, l'une des gemmes les plus rares du monde, taillée en quelques exemplaires de collection.",rar="tres_rare")
# ---------- Borates et gemmes rares ----------
M("Painite","painite","CaZrAl₉O₁₅(BO₃)","Hexagonal","B",(8,8),(4.0,4.01),["rouge brun","rouge foncé"],"vitreux à résineux","aucun","brun rouge","transparent à translucide","conchoïdale","Prismes hexagonaux courts.","Skarns de Mogok (Birmanie).","D'Arthur C. D. Pain, négociant britannique en gemmes, qui la découvrit à Mogok.","Rubis : plus clair, sans zirconium.","Borate de calcium, zirconium et aluminium, longtemps l'espèce la plus rare du monde, avec quelques cristaux connus avant les années 2000.",rar="tres_rare")
M("Jérémejévite","jeremejevite","Al₆(BO₃)₅(F,OH)₃","Hexagonal","B",(6.5,7.5),(3.28,3.3),["incolore","jaune pâle","bleu pâle"],"vitreux","parfait","blanc","transparent","conchoïdale","Prismes allongés hexagonaux.","Pegmatites et veines (Namibie, Nerchinsk, Pamir).","De Pavel Vladimirovitch Eremeev (1830-1899), minéralogiste russe.","Aigue-marine : plus tendre. Apatite bleue : plus tendre.","Borate d'aluminium très rare, taillé en gemmes de collection incolores ou bleu pâle.",rar="tres_rare")
M("Grandidiérite","grandidierite","(Mg,Fe²⁺)Al₃(BO₃)(SiO₄)O₂","Orthorhombique","B",(7,7.5),(2.9,3.0),["vert bleu","bleu pâle","vert"],"vitreux","parfait","blanc","transparent à translucide","irrégulière","Grains, rares cristaux prismatiques.","Pegmatites (Madagascar, Sri Lanka).","D'Alfred Grandidier (1836-1921), explorateur et naturaliste français, qui la découvrit à Madagascar.","Saphir : plus dur. Tourmaline bleue : trigonale.","Borosilicate de magnésium et d'aluminium très rare, vert bleu à fort pléochroïsme, taillé en gemme de collection.",rar="tres_rare")
M("Ludwigite","ludwigite","Mg₂Fe³⁺(BO₃)O₂","Orthorhombique","B",(5,5),(3.7,4.7),["noir verdâtre","noir"],"soyeux à submétallique","aucun","vert noirâtre","opaque","irrégulière","Aiguilles et fibres.","Skarns à bore (Banat, Roumanie ; Mutnovsky, Russie).","D'Ernst Ludwig (1842-1915), chimiste autrichien.","Tourmaline : plus dure.","Borate de magnésium et de fer noir fibreux des skarns.",rar="tres_rare")
M("Inyoite","inyoite","CaB₃O₃(OH)₅·4H₂O","Monoclinique","B",(2,2),(1.9,1.95),["incolore","blanc"],"vitreux","parfait","blanc","transparent","conchoïdale","Cristaux prismatiques, croûtes.","Gisements de borates (Death Valley, Californie ; Turquie ; Chili).","Du comté d'Inyo (Californie).","Colémanite : plus dure.","Borate de calcium hydraté des gisements de borates.",rar="tres_rare")
M("Probertite","probertite","NaCaB₅O₉·5H₂O","Monoclinique","B",(3.5,3.5),(2.14,2.15),["incolore","blanc"],"vitreux à soyeux","parfait","blanc","transparent à translucide","irrégulière","Aiguilles et faisceaux fibreux.","Lacs salés boratés (Death Valley, Kramer, Turquie).","De Frank H. Probert (1876-1940), doyen de l'école d'ingénierie de Berkeley.","Ulexite : plus fibreuse et plus souple.","Borate de sodium et de calcium en faisceaux d'aiguilles.",rar="tres_rare")
M("Priceite","priceite","Ca₄B₁₀O₁₉·7H₂O","Triclinique","B",(3,3.5),(2.4,2.45),["blanc","blanc crayeux"],"terne à soyeux","aucun","blanc","opaque","irrégulière","Nodules en « chou-fleur », masses crayeuses.","Gisements de borates (Oregon, Turquie, Chili).","De Thomas Price (1802-1888), chimiste américain de San Francisco.","Howlite : voir sa fiche.","Borate de calcium crayeux en nodules, souvent confondu avec la howlite.",rar="tres_rare")
M("Sassolite","sassolite","H₃BO₃","Triclinique","B",(1,1),(1.48,1.5),["incolore","blanc","jaune pâle"],"nacré","parfait","blanc","transparent à translucide","irrégulière","Écailles nacrées, croûtes.","Fumerolles et sources chaudes volcaniques (Larderello, Lipari, Vulcano).","De Sasso Pisano (Toscane).","Talc : plus tendre au toucher gras.","Acide borique naturel des fumerolles, en écailles nacrées.",rar="tres_rare")
# ---------- Minéraloïdes ----------
M("Verre du désert de Libye","verre-du-desert-de-libye","SiO₂ (verre)","Amorphe","O",(6,6),(2.2,2.22),["jaune pâle","jaune verdâtre"],"vitreux","aucun","blanc","translucide à transparent","conchoïdale","Fragments et galets vitreux.","Désert de Libye (Grand Erg de sable, Égypte) : verre formé par un impact il y a environ 29 millions d'années.","Du lieu de découverte, le désert de Libye.","Obsidienne : plus foncée, d'origine volcanique.","Verre presque pur de silice, formé par l'impact d'une météorite ou l'explosion d'un astéroïde dans l'atmosphère ; un scarabée taillé dans ce verre orne un pectoral de Toutânkhamon.",rar="tres_rare")
M("Bois silicifié","bois-silicifie","SiO₂ (opale, calcédoine, quartz)","Variable","O",(6.5,7),(2.5,2.9),["brun","rouge","jaune","gris","noir"],"vitreux à terne","aucun","blanc","opaque à translucide","conchoïdale à esquilleuse","Troncs et fragments qui conservent la structure du bois.","Troncs enfouis dans des cendres volcaniques ou des sédiments siliceux (Arizona, Madagascar, Indonésie, Égypte).","Du bois remplacé par de la silice.","Bois fossilisé par du carbonate : plus tendre.","Bois fossile transformé en silice, dont les cernes et les cellules restent visibles ; il se taille et se polit.",rar="rare")
if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    seen = set()
    for m in OUT:
        assert m["slug"] not in seen, m["slug"]; seen.add(m["slug"])
    json.dump(OUT, open(os.path.join(here, "lot6.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    def lit(v):
        if v is None: return "null"
        if isinstance(v, bool): return "true" if v else "false"
        if isinstance(v, (int, float)): return str(v)
        if isinstance(v, list): return "array[" + ",".join("'" + s.replace("'", "''") + "'" for s in v) + "]::text[]"
        return "'" + str(v).replace("'", "''") + "'"
    cols = ["name","slug","formula","crystal_system","chemical_class","rarity","hardness","hardness_max","density","density_max","colors","luster","cleavage","streak","transparency","fracture","fluorescence","habit","formation","etymology","varieties","confusions","description","mineral_group","is_group"]
    rows = ",\n".join("  (" + ", ".join(lit(m[c]) for c in cols) + ", 'published')" for m in OUT)
    sql = f"-- {len(OUT)} fiches de minéraux célèbres encore absentes (tellurures, halogénures de plomb-cuivre, carbonates et sulfates rares, phosphates de pegmatites, silicates de collection, gemmes rares, minéraux de météorites, minéraloïdes).\n-- Une fiche déjà présente (même nom ou même slug) n'est pas modifiée. Photos libres à ajouter ensuite (tools/images/find-mineral-photos.mjs ou administration).\ninsert into public.minerals ({', '.join(cols)}, publication_status) values\n{rows}\non conflict do nothing;\n"
    open(os.path.join(here, "../../supabase/migrations/20261005200000_minerals_lot6.sql"), "w", encoding="utf-8").write(sql)
    print(len(OUT), "fiches")
