# Glossaire, lot 2 : minéralogie. Chaque terme : (terme, définition, termes liés, minéraux d'exemple).
TERMS = [
# Disciplines, nomenclature, classement
("Minéralogie", "Science qui étudie les minéraux : leur composition, leur structure, leurs propriétés, leur origine et leur classement.", "Minéral,Espèce minérale,Cristallographie,Gisement", ""),
("Gemmologie", "Étude des gemmes : leur identification, leur évaluation, leurs traitements et leurs imitations. Elle s'appuie sur la minéralogie mais s'intéresse surtout aux pierres taillées.", "Gemme,Pierre précieuse,Traitement,Synthétique", ""),
("Cristallochimie", "Étude des liens entre la composition chimique d'un minéral et la structure de son cristal. Elle explique, par exemple, pourquoi deux minéraux voisins ont des propriétés différentes.", "Structure cristalline,Isomorphisme,Formule chimique", ""),
("Classification de Strunz", "Système de classement des minéraux fondé sur leur composition chimique et leur structure. Il distingue notamment les éléments natifs, les sulfures, les halogénures, les oxydes, les carbonates, les sulfates, les phosphates et les silicates.", "Espèce minérale,Élément natif,Silicate", ""),
("Classification de Dana", "Système de classement des minéraux fondé sur leur composition chimique, créé aux États-Unis par la famille Dana. Il sert de référence, comme la classification de Strunz.", "Classification de Strunz,Espèce minérale", ""),
("Nomenclature minérale", "Règles qui encadrent le nom des minéraux. L'IMA valide chaque nouveau nom et la description de l'espèce.", "IMA,Espèce minérale,Éponyme", ""),
("Éponyme", "Se dit d'un nom de minéral donné en hommage à une personne, à un lieu ou à une institution. La goethite honore Goethe, et la franklinite la ville de Franklin.", "Nomenclature minérale,IMA,Localité type", "Goethite"),
("Minéral discrédité", "Espèce dont l'IMA a retiré la reconnaissance, parce qu'elle s'est révélée être un mélange, un synonyme ou une erreur d'analyse. Son nom ne doit plus servir d'espèce.", "IMA,Espèce minérale,Variété", ""),
("Holotype", "Échantillon unique sur lequel une espèce minérale nouvelle a été décrite. Il est conservé dans un musée ou une collection publique.", "Localité type,Espèce minérale,IMA", ""),
("Synonyme", "Autre nom donné au même minéral. Un synonyme ancien ou régional peut subsister dans les collections alors que l'IMA n'en retient qu'un.", "Variété,Espèce minérale,Nomenclature minérale", ""),
("Sous-groupe", "Division d'un groupe minéral qui rassemble les espèces les plus proches par leur composition. Dans le groupe des grenats, on distingue par exemple les grenats alumineux.", "Groupe minéral,Espèce minérale,Série", "Grenat"),
("Pôle d'une série", "Composition extrême d'une série de solution solide. Les termes intermédiaires se situent entre deux pôles.", "Série,Solution solide,Isomorphisme", ""),
("Minéral accessoire", "Minéral présent en très petite quantité dans une roche, comme le zircon ou l'apatite dans un granite. Il ne définit pas la roche.", "Minéral,Roche,Minéral essentiel", "Zircon,Apatite"),
("Minéral essentiel", "Minéral qui définit une roche, parce qu'il en forme une part importante. Le quartz, le feldspath et le mica sont les minéraux essentiels du granite.", "Minéral accessoire,Roche,Granite", "Quartz,Mica"),
# Propriétés optiques et lumineuses
("Chromophore", "Élément chimique, ou défaut du cristal, responsable de la couleur d'un minéral : fer, chrome, cuivre, manganèse, titane.", "Couleur,Allochromatique,Idiochromatique,Centre coloré", ""),
("Pseudochromatique", "Se dit d'une couleur due non à la composition chimique mais à des phénomènes physiques : fines inclusions, réseau, diffraction, interférences. L'opale précieuse en offre un exemple.", "Idiochromatique,Allochromatique,Irisation", "Opale"),
("Dichroïsme", "Propriété d'un cristal qui montre deux couleurs différentes selon la direction d'observation. C'est un cas particulier du pléochroïsme.", "Pléochroïsme,Cristal uniaxe,Dichroscope", "Cordiérite,Tourmaline"),
("Trichroïsme", "Propriété d'un cristal qui montre trois couleurs différentes selon la direction d'observation. Elle concerne les cristaux biaxes.", "Pléochroïsme,Dichroïsme,Cristal biaxe", "Cordiérite"),
("Photosensibilité", "Propriété d'un minéral dont la couleur change ou s'estompe à la lumière ou à la chaleur. Certains quartz roses, certaines améthystes et certaines kunzites pâlissent au soleil.", "Couleur,Centre coloré,Ultraviolets", "Quartz rose,Améthyste,Kunzite"),
("Thermoluminescence", "Lumière émise par un minéral chauffé doucement après avoir été irradié. Certaines fluorines et certaines calcites s'illuminent ainsi.", "Luminescence,Fluorescence,Triboluminescence", "Fluorine,Calcite"),
("Cathodoluminescence", "Lumière émise par un minéral bombardé d'électrons. Elle sert en laboratoire à révéler les zones de croissance des cristaux.", "Luminescence,Zonage,Fluorescence", ""),
("Aventurescence", "Scintillement dû à de minuscules inclusions de paillettes qui réfléchissent la lumière à l'intérieur de la pierre. La pierre de soleil et l'aventurine en sont deux exemples.", "Inclusion,Paillette,Chatoyance", "Aventurine,Pierre de soleil"),
("Opalescence", "Reflet laiteux et bleuté d'une pierre, dû à la diffusion de la lumière par de très fines particules. L'opale commune laiteuse en montre.", "Adularescence,Irisation,Translucide", "Opale"),
("Schiller", "Reflet métallique ou nacré qui se déplace à la surface d'un minéral selon l'éclairage, dû à des lamelles minuscules à l'intérieur. Il est typique de l'hypersthène et du labrador.", "Labradorescence,Adularescence,Chatoyance", "Labradorite"),
("Diaphane", "Se dit d'un minéral qui laisse passer la lumière sans permettre de distinguer nettement les objets qu'on regarde au travers. Synonyme de translucide.", "Translucide,Transparent,Opaque", ""),
("Hyalin", "Se dit d'un minéral clair et transparent comme du verre. On appelle ainsi le quartz hyalin, ou cristal de roche.", "Transparent,Éclat vitreux,Limpide", "Quartz"),
("Limpide", "Se dit d'un cristal parfaitement clair, sans fêlure ni inclusion visible.", "Transparent,Hyalin,Qualité gemme", ""),
("Laiteux", "Se dit d'un minéral blanc et translucide comme du lait, à cause de fines inclusions ou de bulles de fluide.", "Translucide,Inclusion fluide,Opalescence", "Quartz"),
("Qualité gemme", "Qualité d'un cristal transparent et net, assez pur pour être taillé en gemme. On dit qu'un cristal est gemmé.", "Gemme,Transparent,Limpide", ""),
# Autres propriétés physiques
("Masse volumique", "Masse d'un minéral par unité de volume, exprimée en grammes par centimètre cube. Divisée par la masse volumique de l'eau, elle donne la densité.", "Densité,Poids spécifique,Balance hydrostatique", ""),
("Poids spécifique", "Autre nom de la densité d'un minéral : rapport entre sa masse et celle d'un même volume d'eau.", "Densité,Masse volumique,Balance hydrostatique", ""),
("Balance hydrostatique", "Balance qui pèse un minéral dans l'air puis dans l'eau, ce qui permet de calculer sa densité par la différence des deux pesées.", "Densité,Masse volumique,Liqueur dense", ""),
("Liqueur dense", "Liquide très dense dans lequel on plonge un minéral pour estimer sa densité : il flotte ou coule selon qu'il est plus ou moins dense que le liquide. Elle sert aussi à séparer des minéraux.", "Densité,Balance hydrostatique,Masse volumique", ""),
("Solubilité", "Capacité d'un minéral à se dissoudre dans un liquide, l'eau le plus souvent. La halite se dissout dans l'eau, le quartz presque pas.", "Hygroscopique,Efflorescence,Dissolution", "Halite"),
("Hygroscopique", "Se dit d'un minéral qui absorbe l'humidité de l'air. Il doit être conservé au sec.", "Solubilité,Déliquescent,Efflorescence", "Halite"),
("Déliquescent", "Se dit d'un minéral qui absorbe tant d'humidité de l'air qu'il finit par se dissoudre dans cette eau.", "Hygroscopique,Solubilité,Efflorescence", ""),
("Minéral hydraté", "Minéral qui contient de l'eau dans sa structure, sous forme de molécules ou de groupes hydroxyle. Le gypse et la turquoise sont hydratés.", "Eau de cristallisation,Anhydre,Hydroxyde", "Gypse,Turquoise"),
("Eau de cristallisation", "Molécules d'eau intégrées à la structure d'un cristal. Un minéral qui en perd par la chaleur ou la sécheresse peut s'altérer.", "Minéral hydraté,Anhydre,Déshydratation", "Gypse"),
("Anhydre", "Se dit d'un minéral qui ne contient pas d'eau dans sa structure. L'anhydrite est le sulfate de calcium sans eau, par opposition au gypse.", "Minéral hydraté,Eau de cristallisation,Sulfate", "Anhydrite,Gypse"),
("Déshydratation", "Perte d'eau d'un minéral hydraté, par la chaleur ou l'air sec. Elle peut le faire changer d'aspect, de couleur ou de forme.", "Eau de cristallisation,Minéral hydraté,Efflorescence", ""),
("Fusibilité", "Facilité avec laquelle un minéral fond à la flamme. Une échelle à six degrés, dite de von Kobell, permet de la comparer.", "Test au chalumeau,Test à la flamme", ""),
("Test à la flamme", "Observation de la couleur que prend une flamme quand on y chauffe un fragment de minéral. Le cuivre colore la flamme en vert, le sodium en jaune, le strontium en rouge.", "Test au chalumeau,Fusibilité", "Malachite,Halite"),
("Test au chalumeau", "Chauffage d'un fragment de minéral à l'aide d'un chalumeau pour observer comment il fond, change de couleur ou dégage une odeur. Les minéralogistes l'utilisaient beaucoup avant les analyses modernes.", "Fusibilité,Test à la flamme", ""),
("Test à l'acide", "Dépôt d'une goutte d'acide dilué sur un minéral pour observer s'il fait de la mousse. Les carbonates, comme la calcite, effervescent.", "Effervescence,Carbonate", "Calcite"),
("Plaque de porcelaine", "Plaquette de porcelaine blanche non émaillée sur laquelle on frotte un minéral pour observer la couleur de sa poudre, ou trait.", "Trait,Couleur,Dureté", ""),
("Pointe de dureté", "Petit outil à pointe (crayon d'acier ou de minéral) dont la dureté est connue et qui sert à rayer un minéral pour situer sa dureté sur l'échelle de Mohs.", "Dureté,Échelle de Mohs", ""),
("Paramagnétisme", "Propriété d'un minéral faiblement attiré par un aimant très puissant, mais pas par un simple aimant de poche. Beaucoup de minéraux riches en fer en font preuve.", "Magnétisme,Ferromagnétisme", ""),
("Ferromagnétisme", "Propriété d'un minéral fortement attiré par un aimant ordinaire. La magnétite est le minéral ferromagnétique le plus courant.", "Magnétisme,Paramagnétisme", "Magnétite"),
# Ténacité, cassure, clivage
("Fragile", "Se dit d'un minéral qui se brise ou s'effrite sous un choc ou une pression. C'est la ténacité la plus courante chez les minéraux.", "Ténacité,Friable,Ductile", "Quartz"),
("Friable", "Se dit d'un minéral qui s'écrase facilement en poudre entre les doigts.", "Fragile,Ténacité,Pulvérulent", ""),
("Ductile", "Se dit d'un minéral qui peut s'étirer en fil sans casser. Le cuivre natif et l'or le sont.", "Malléable,Ténacité,Élément natif", "Or,Cuivre natif"),
("Tenace", "Se dit d'un minéral qui résiste aux chocs et qui est difficile à casser. La jadéite et la néphrite sont remarquablement tenaces.", "Ténacité,Fragile,Dureté", "Jadéite"),
("Cassure crochue", "Cassure qui laisse une surface déchiquetée, à pointes coupantes. Elle est typique des métaux natifs ductiles, comme le cuivre natif.", "Cassure,Ductile,Élément natif", "Cuivre natif"),
("Cassure fibreuse", "Cassure qui se fait en fibres ou en esquilles très fines, comme dans le bois. On l'observe dans la serpentine fibreuse ou le gypse fibreux.", "Cassure,Cassure esquilleuse,Fibreux", "Gypse"),
("Clivage cubique", "Trois directions de clivage à angle droit, qui produisent des fragments en forme de cubes. La halite et la galène se clivent ainsi.", "Clivage,Clivage parfait,Cubique", "Halite,Galène"),
("Clivage prismatique", "Clivage parallèle aux faces d'un prisme, qui produit des fragments allongés à section en losange ou en rectangle. Il est typique des amphiboles.", "Clivage,Prisme,Amphibole", "Hornblende"),
("Clivage pinacoïdal", "Clivage parallèle à une paire de faces opposées, qui produit de grandes lames planes. Le mica et le gypse se clivent ainsi.", "Clivage,Clivage basal,Pinacoïde", "Mica,Gypse"),
("Clivage dodécaédrique", "Clivage en six directions, parallèle aux faces d'un dodécaèdre. Il est caractéristique de la sphalérite.", "Clivage,Dodécaèdre,Rhombododécaèdre", "Sphalérite"),
# Habitus, textures
("Mamelonné", "Se dit d'une surface formée de petites bosses arrondies, comme la malachite, la goethite ou l'hématite.", "Botryoïdal,Réniforme,Habitus", "Malachite,Goethite,Hématite"),
("Coralloïde", "Se dit d'un minéral aux branches arrondies comme un corail. L'aragonite en « fleur de fer » en est un exemple.", "Habitus,Dendrite,Stalactite", "Aragonite"),
("Filiforme", "Se dit d'un minéral en fils fins, flexibles ou raides. Le cuivre natif et l'argent natif forment souvent des cristaux filiformes.", "Capillaire,Aciculaire,Habitus", "Cuivre natif,Argent natif"),
("Arborescent", "Se dit d'un groupe de cristaux ramifiés comme un arbre. Les dendrites, le cuivre natif et l'argent natif prennent cette forme.", "Dendrite,Habitus,Filiforme", "Cuivre natif,Argent natif"),
("Colonnaire", "Se dit d'un minéral formé de colonnes serrées, parallèles ou en éventail, comme certains agrégats de calcite, de tourmaline ou de béryl.", "Prismatique,Habitus,Agrégat cristallin", "Calcite,Tourmaline"),
("Sphérolitique", "Se dit d'un minéral en petites sphères formées de fibres rayonnant depuis un centre. La malachite et la wavellite en donnent des exemples.", "Fibro-radié,Rosette,Habitus", "Wavellite,Malachite"),
("Pisolitique", "Se dit d'un minéral formé de petites boules de la taille d'un pois, faites de couches concentriques, comme certaines bauxites.", "Oolithique,Concrétion,Habitus", "Bauxite"),
("Oolithique", "Se dit d'un minéral ou d'une roche formés de grains minuscules arrondis, faits de couches concentriques, comme les œufs d'un poisson.", "Pisolitique,Concrétion,Habitus", ""),
("Squelettique", "Se dit d'un cristal dont les arêtes ont grandi plus vite que les faces, ce qui laisse des creux.", "Cristal squelettique,Croissance en trémie,Habitus", ""),
("Pulvérulent", "Se dit d'un minéral en poudre fine, sans cohésion, qui se dépose en enduit ou en croûte.", "Friable,Enduit,Habitus", ""),
("Radié", "Se dit d'un agrégat dont les cristaux rayonnent à partir d'un centre, comme les rayons d'une roue.", "Fibro-radié,Rosette,Gerbe", "Stibine,Pyrite"),
("Équant", "Se dit d'un cristal dont les trois dimensions sont à peu près égales, comme un cube ou un octaèdre, par opposition aux cristaux allongés ou aplatis.", "Habitus,Cubique,Octaèdre", ""),
("Bacillaire", "Se dit d'un cristal allongé en bâtonnet, plus épais qu'une aiguille.", "Aciculaire,Prismatique,Habitus", ""),
("Géodique", "Se dit d'un minéral qui tapisse l'intérieur d'une cavité, ou d'une roche creuse comme une géode.", "Géode,Druse,Amygdale", "Quartz,Améthyste"),
("Étoilé", "Se dit d'un agrégat de cristaux disposés en étoile autour d'un point, comme les macles cycliques de certains minéraux.", "Macle cyclique,Radié,Rosette", ""),
("Rubané", "Se dit d'un minéral ou d'une roche qui montre des bandes parallèles de couleurs ou de textures différentes, comme l'agate ou l'onyx.", "Zonage,Concrétion,Couleur", "Agate,Onyx"),
("Cristallin", "Se dit d'un minéral ou d'une roche constitués de cristaux visibles, par opposition à une substance sans forme cristalline.", "Cryptocristallin,Microcristallin,Amorphe", ""),
("Microcristallin", "Se dit d'un minéral formé de cristaux trop petits pour être vus à l'œil nu, mais visibles au microscope ou à la loupe.", "Cryptocristallin,Cristallin,Granulaire", "Calcédoine"),
("Cryptocristallin", "Se dit d'un minéral formé de cristaux si petits qu'ils ne se distinguent même pas au microscope ordinaire. La calcédoine en est un exemple.", "Microcristallin,Amorphe,Cristallin", "Calcédoine"),
# Familles chimiques
("Oxyde", "Minéral où un ou plusieurs métaux sont combinés à de l'oxygène. L'hématite, la magnétite, le corindon et la cuprite en sont des exemples.", "Oxyde et hydroxyde,Hydroxyde,Élément natif", "Hématite,Magnétite,Corindon"),
("Hydroxyde", "Minéral où un métal est combiné au groupe hydroxyle OH. La goethite et la brucite sont des hydroxydes.", "Oxyde,Oxyde et hydroxyde,Minéral hydraté", "Goethite,Brucite"),
("Chlorure", "Halogénure où un métal est combiné au chlore. La halite et la sylvite sont des chlorures.", "Halogénure,Fluorure,Évaporite", "Halite,Sylvite"),
("Fluorure", "Halogénure où un métal est combiné au fluor. La fluorine est le fluorure le plus connu.", "Halogénure,Chlorure,Fluorescence", "Fluorine"),
("Arséniate", "Minéral dont l'anion principal est le groupe AsO₄, voisin du phosphate. Beaucoup d'arséniates, secondaires et colorés, se forment dans la zone d'oxydation des gisements.", "Phosphate,Vanadate,Zone d'oxydation", "Érythrine,Annabergite,Mimétite"),
("Vanadate", "Minéral dont l'anion principal est le groupe VO₄. La vanadinite en est l'exemple le plus connu.", "Phosphate,Arséniate,Zone d'oxydation", "Vanadinite"),
("Chromate", "Minéral dont l'anion principal est le groupe CrO₄. La crocoïte, rouge orangé, est un chromate de plomb.", "Sulfate,Zone d'oxydation,Oxyde", "Crocoïte"),
("Tungstate", "Minéral dont l'anion principal est le groupe WO₄. La scheelite et la wolframite sont les principaux tungstates, minerais de tungstène.", "Molybdate,Minerai,Fluorescence", "Scheelite,Wolframite"),
("Molybdate", "Minéral dont l'anion principal est le groupe MoO₄. La wulfénite, orange à jaune, est un molybdate de plomb.", "Tungstate,Chromate,Zone d'oxydation", "Wulfénite"),
("Nitrate", "Minéral dont l'anion principal est le groupe NO₃. Très solubles, les nitrates se forment surtout dans les régions très sèches.", "Évaporite,Solubilité,Sulfate", "Nitratine"),
("Séléniure", "Minéral où le sélénium est combiné à des métaux. Les séléniures sont rares et souvent associés aux sulfures.", "Sulfure,Tellurure,Sulfosel", ""),
("Tellurure", "Minéral où le tellure est combiné à des métaux. Les tellurures sont parmi les minerais d'or et d'argent de certains gisements.", "Sulfure,Séléniure,Élément natif", ""),
("Arséniure", "Minéral où l'arsenic est combiné à des métaux. La nickéline et la skutterudite sont des arséniures.", "Sulfure,Sulfosel,Élément natif", "Nickéline,Skutterudite"),
("Sulfarséniure", "Minéral où le soufre et l'arsenic sont combinés à un métal. L'arsénopyrite et la cobaltite en sont des exemples.", "Sulfure,Arséniure,Sulfosel", "Arsénopyrite,Cobaltite"),
("Aluminosilicate", "Silicate qui contient de l'aluminium dans sa structure. Les feldspaths, les micas, les grenats et les zéolites en sont.", "Silicate,Feldspath,Mica", "Feldspath,Mica"),
("Silice", "Dioxyde de silicium, de formule SiO₂. Elle forme le quartz et ses variétés, la calcédoine, l'opale et les verres naturels.", "Silicate,Silex,Quartzite", "Quartz,Opale"),
("Métal natif", "Métal présent à l'état pur dans la nature, comme l'or, l'argent, le cuivre, le platine ou le fer.", "Élément natif,Pépite,Ductile", "Or,Argent,Cuivre natif"),
("Semi-métal", "Élément aux propriétés intermédiaires entre un métal et un non-métal, comme l'arsenic, l'antimoine, le bismuth ou le tellure. On les trouve parfois natifs.", "Élément natif,Métal natif", "Arsenic,Antimoine,Bismuth"),
("Métal précieux", "Métal rare, résistant à la corrosion et très recherché : or, argent, platine et métaux de la même famille.", "Métal natif,Pépite,Placer", "Or,Argent,Platine"),
("Terres rares", "Groupe de 17 éléments chimiques aux propriétés voisines (lanthane, cérium, néodyme…). Ils se concentrent dans quelques minéraux comme la monazite et la bastnaésite.", "Élément chimique,Minerai,Radioactivité", "Monazite,Bastnaésite"),
("Substitution", "Remplacement d'un atome par un autre de taille et de charge voisines dans la structure d'un cristal. Elle explique les séries de solution solide et les différences de couleur.", "Isomorphisme,Solution solide,Série", ""),
("Impureté", "Atome étranger présent en petite quantité dans un cristal. Elle peut colorer le minéral sans changer son espèce.", "Chromophore,Allochromatique,Substitution", ""),
("Élément trace", "Élément présent en très faible quantité dans un minéral, souvent quelques grammes par tonne. Il renseigne sur l'origine du cristal.", "Impureté,Substitution,Élément chimique", ""),
# Outils et analyses
("Polariscope", "Instrument à deux filtres polarisants qui permet de savoir si une pierre est simplement ou doublement réfractante, donc de distinguer un verre d'un cristal.", "Lumière polarisée,Biréfringence,Isotrope", ""),
("Réfractomètre", "Instrument qui mesure l'indice de réfraction d'une gemme à facette plane. Il aide à identifier la pierre.", "Indice de réfraction,Gemmologie,Biréfringence", ""),
("Dichroscope", "Petit instrument à loupe qui montre côte à côte les deux couleurs d'une pierre dichroïque. Il aide à identifier les gemmes.", "Dichroïsme,Pléochroïsme,Gemmologie", ""),
("Spectroscope", "Instrument qui décompose la lumière traversant une pierre pour montrer les raies sombres d'absorption. Ces raies aident à identifier certaines gemmes.", "Gemmologie,Couleur,Chromophore", ""),
("Microscope polarisant", "Microscope muni de deux filtres polarisants, utilisé pour observer des minéraux en lame mince ou en grains et déterminer leurs propriétés optiques.", "Lame mince,Lumière polarisée,Extinction", ""),
("Lame mince", "Tranche de roche collée sur du verre et amincie à 30 millièmes de millimètre, assez fine pour laisser passer la lumière. On l'observe au microscope polarisant.", "Microscope polarisant,Roche,Pétrologie", ""),
("Section polie", "Surface de roche ou de minerai polie en miroir pour observer ses minéraux opaques au microscope en lumière réfléchie.", "Lame mince,Minerai,Opaque", ""),
("Spectroscopie Raman", "Technique d'analyse qui envoie un laser sur un minéral et mesure la lumière qu'il renvoie. Chaque espèce renvoie une signature, ce qui permet de l'identifier sans l'abîmer.", "Diffraction des rayons X,Analyse chimique", ""),
("Microsonde électronique", "Appareil qui envoie un faisceau d'électrons sur un point minuscule d'un minéral pour en mesurer la composition chimique.", "Analyse chimique,Formule chimique,Microscopie électronique à balayage", ""),
("Microscopie électronique à balayage", "Technique qui balaie un minéral avec un faisceau d'électrons pour en produire des images très agrandies, jusqu'à plusieurs dizaines de milliers de fois. Elle porte aussi le sigle MEB.", "Microsonde électronique,Analyse chimique", ""),
("Fluorescence X", "Technique d'analyse qui éclaire un minéral par des rayons X et mesure les rayons secondaires qu'il émet, ce qui donne sa composition chimique sans l'abîmer.", "Analyse chimique,Diffraction des rayons X", ""),
("Analyse chimique", "Mesure des éléments qui composent un minéral. Elle permet de confirmer l'espèce et d'établir sa formule chimique.", "Formule chimique,Microsonde électronique,Fluorescence X", ""),
# Gemmes
("Facette", "Petite face plane polie sur une gemme taillée. Leur nombre et leur disposition déterminent l'éclat de la pierre.", "Taille,Gemme,Taille brillant", ""),
("Table", "Grande facette plane au sommet d'une gemme taillée, par laquelle on regarde la pierre.", "Facette,Couronne,Pavillon", ""),
("Couronne", "Partie supérieure d'une gemme taillée, située au-dessus du rondiste, entre la table et le bord de la pierre.", "Table,Pavillon,Rondiste", ""),
("Pavillon", "Partie inférieure d'une gemme taillée, sous le rondiste, qui se termine en pointe ou en arête.", "Couronne,Rondiste,Table", ""),
("Rondiste", "Tranche étroite qui sépare la couronne et le pavillon d'une gemme taillée et qui permet de la sertir.", "Couronne,Pavillon,Facette", ""),
("Taille brillant", "Taille à 57 ou 58 facettes, conçue pour renvoyer le maximum de lumière. Elle est la plus courante pour le diamant.", "Taille,Facette,Éclat adamantin", "Diamant"),
("Taille émeraude", "Taille rectangulaire à pans coupés et facettes parallèles, en escalier, qui met en valeur la couleur et la transparence. Elle est classique pour l'émeraude.", "Taille,Facette,Gemme", "Émeraude"),
("Pureté", "Degré de netteté d'une gemme : absence ou présence d'inclusions et de défauts visibles. Elle compte avec la couleur, la taille et le poids pour évaluer une pierre.", "Inclusion,Gemme,Carat", ""),
("Imitation", "Matière qui ressemble à une gemme sans en avoir la nature : verre, plastique ou autre minéral. À distinguer de la pierre synthétique, qui a la même composition que la gemme naturelle.", "Synthétique,Gemmologie,Gemme", ""),
("Doublet", "Pierre assemblée de deux parties collées l'une à l'autre, par exemple une fine tranche de gemme sur un support de verre.", "Triplet,Imitation,Gemmologie", ""),
("Triplet", "Pierre assemblée de trois parties collées : généralement une tranche de pierre naturelle, un support et une coiffe transparente.", "Doublet,Imitation,Gemmologie", ""),
("Pierre de couleur", "Gemme autre que le diamant, appréciée pour sa couleur : saphir, émeraude, rubis, tourmaline, grenat, topaze.", "Gemme,Pierre précieuse,Pierre fine", "Saphir,Émeraude,Rubis"),
("Gemme organique", "Matière d'origine vivante utilisée en joaillerie : perle, corail, ambre, jais. Elle n'est pas un minéral, ou seulement en partie.", "Gemme,Minéraloïde,Ambre", ""),
("Ambre", "Résine fossile d'arbres, vieille de plusieurs dizaines de millions d'années, qui contient parfois des insectes. Ce n'est pas un minéral mais un minéraloïde.", "Minéraloïde,Gemme organique,Fossile", ""),
("Huilage", "Traitement qui remplit les fissures d'une gemme avec de l'huile pour les rendre moins visibles. Il est courant sur les émeraudes.", "Traitement,Gemmologie,Inclusion", "Émeraude"),
("Comblement", "Traitement qui remplit les fissures ou les cavités d'une gemme avec du verre ou une résine pour améliorer son aspect. Il doit être signalé à l'acheteur.", "Traitement,Huilage,Gemmologie", ""),
("Irradiation", "Exposition d'une pierre à des rayonnements pour changer sa couleur. Elle existe dans la nature et se pratique aussi en laboratoire.", "Traitement,Centre coloré,Photosensibilité", "Topaze,Quartz"),
("Certificat gemmologique", "Document établi par un laboratoire qui identifie une gemme, décrit ses caractéristiques et indique si elle a été traitée.", "Gemmologie,Traitement,Carat", ""),
# Collection
("Provenance", "Lieu d'où vient un spécimen, et par extension le parcours de la pièce depuis sa découverte. Elle est essentielle pour le collectionneur (la collectionneuse) et pour la documentation.", "Localité type,Étiquette,Spécimen", ""),
("Pièce de cabinet", "Spécimen de belle taille, esthétique, destiné à être montré dans une vitrine. Il se situe entre le format miniature et la grande pièce de musée.", "Formats de collection,Spécimen,Micromonté", ""),
("Préparation", "Travail qui dégage un cristal ou un spécimen de sa gangue ou nettoie sa surface, à l'outil, à l'air comprimé ou avec des produits adaptés. Elle demande de la patience et du soin.", "Nettoyage,Gangue,Spécimen", ""),
("Réparation", "Collage d'un cristal cassé ou recollage d'un fragment sur sa matrice avec une colle adaptée. Elle doit être invisible et signalée dans l'étiquette du spécimen.", "Spécimen,Étiquette,Nettoyage", ""),
("Soclage", "Fixation d'un spécimen sur un socle, en bois, en pierre ou en acrylique, pour le présenter sans l'abîmer.", "Spécimen,Pièce de cabinet,Étiquette", ""),
("Numéro d'inventaire", "Numéro unique attribué à chaque spécimen de collection, noté sur la pièce et dans le catalogue pour l'identifier et suivre son histoire.", "Étiquette,Provenance,Spécimen", ""),
("Cabinet de minéralogie", "Collection de minéraux conservée dans un meuble ou une salle, à l'origine par des amateurs éclairés du XVIIIᵉ siècle, aujourd'hui dans les musées et les universités.", "Spécimen,Collection,Pièce de cabinet", ""),
("Conservation des minéraux", "Ensemble des précautions qui préservent les spécimens : éviter la lumière directe, l'humidité, la chaleur et les chocs, et isoler les minéraux fragiles ou instables.", "Photosensibilité,Maladie de la pyrite,Hygroscopique", ""),
("Minéral toxique", "Minéral qui contient un élément dangereux (arsenic, plomb, mercure, amiante…). Il se manipule avec précaution, on se lave les mains après et on ne le met jamais en bouche.", "Amiante,Radioactivité,Conservation des minéraux", ""),
]
