# Glossaire, lot 2 : géologie. Chaque terme : (terme, définition, termes liés, minéraux d'exemple).
TERMS = [
# Disciplines
("Géologie", "Science qui étudie la Terre : sa structure, ses roches, son histoire et les phénomènes qui la transforment.", "Roche,Minéral,Tectonique des plaques,Échelle des temps géologiques", ""),
("Pétrologie", "Étude des roches : leur composition, leur texture, leur origine et leur évolution.", "Roche,Roche magmatique,Roche sédimentaire,Roche métamorphique", ""),
("Géochimie", "Étude de la répartition et du comportement des éléments chimiques dans la Terre, les roches et les minéraux.", "Élément chimique,Élément trace,Isotope", ""),
("Paléontologie", "Science qui étudie les êtres vivants du passé à travers leurs fossiles.", "Fossile,Fossilisation,Échelle des temps géologiques", ""),
("Stratigraphie", "Étude de la succession des couches de roches et de leur âge, qui permet de reconstituer l'histoire d'une région.", "Strate,Fossile stratigraphique,Échelle des temps géologiques", ""),
("Tectonique", "Étude des déformations de la croûte terrestre : plis, failles, chaînes de montagnes.", "Tectonique des plaques,Faille,Pli", ""),
("Volcanologie", "Étude des volcans, des éruptions et des roches volcaniques.", "Volcanisme,Lave,Roche volcanique", ""),
("Sédimentologie", "Étude des sédiments et des roches sédimentaires : leur origine, leur transport, leur dépôt.", "Sédiment,Sédimentation,Roche sédimentaire", ""),
("Gîtologie", "Étude des gisements de minéraux utiles : leur formation, leur forme, leur répartition et les moyens de les trouver.", "Gisement,Gîte,Minerai", ""),
("Métallogénie", "Étude de l'origine des gisements de métaux et des conditions géologiques qui les ont concentrés.", "Gîtologie,Gisement,Minerai", ""),
("Géophysique", "Étude de la Terre par des mesures physiques : ondes sismiques, gravité, magnétisme, chaleur.", "Sismologie,Lithosphère,Noyau terrestre", ""),
("Sismologie", "Étude des séismes et de la propagation des ondes qu'ils produisent dans la Terre. Elle a révélé la structure interne du globe.", "Séisme,Faille,Géophysique", ""),
("Géomorphologie", "Étude des formes du relief et des processus qui les façonnent : érosion, glaciers, rivières, volcans.", "Érosion,Karst,Moraine", ""),
("Hydrogéologie", "Étude des eaux souterraines : leur circulation dans les roches et leur rôle dans la formation de certains minéraux.", "Karst,Source thermale,Spéléothème", ""),
("Géologie structurale", "Étude de la forme et de la déformation des corps de roche : plis, failles, joints, schistosité.", "Tectonique,Pli,Faille", ""),
("Carte géologique", "Carte qui montre la nature et l'âge des roches qui affleurent à la surface du sol. En France, elle est éditée par le BRGM, au 1/50 000.", "Affleurement,Coupe géologique,Roche", ""),
("Coupe géologique", "Dessin qui montre la succession des couches de roches en profondeur le long d'une ligne, comme une tranche du sous-sol.", "Carte géologique,Strate,Pendage", ""),
("Marteau de géologue", "Marteau à tête plate d'un côté et pointue ou en burin de l'autre, outil de base pour détacher des échantillons de roche.", "Massette,Burin,Échantillon", ""),
("Échantillon", "Morceau de roche ou de minéral prélevé pour être étudié, analysé ou conservé.", "Spécimen,Marteau de géologue,Étiquette", ""),
("Carotte", "Cylindre de roche extrait du sous-sol par un forage, qui permet d'étudier les couches traversées.", "Sondage,Strate,Gisement", ""),
("Sondage", "Forage destiné à reconnaître le sous-sol, à rechercher un gisement ou à prélever des échantillons.", "Carotte,Prospection,Gisement", ""),
# Structure de la Terre et tectonique
("Lithosphère", "Enveloppe rigide de la Terre, formée de la croûte et de la partie supérieure du manteau, découpée en plaques qui se déplacent.", "Croûte continentale,Croûte océanique,Tectonique des plaques,Asthénosphère", ""),
("Asthénosphère", "Couche du manteau située sous la lithosphère, assez ductile pour s'écouler très lentement. Les plaques glissent dessus.", "Lithosphère,Manteau,Tectonique des plaques", ""),
("Noyau terrestre", "Partie centrale de la Terre, faite surtout de fer et de nickel, avec une partie externe liquide et une graine interne solide.", "Manteau,Croûte continentale,Géophysique", ""),
("Croûte continentale", "Partie superficielle des continents, épaisse en moyenne de 30 à 40 kilomètres, faite surtout de roches granitiques et métamorphiques.", "Croûte océanique,Lithosphère,Granite", ""),
("Croûte océanique", "Partie superficielle du fond des océans, épaisse de 6 à 7 kilomètres, faite surtout de basalte et de gabbro. Elle est plus dense et plus jeune que la croûte continentale.", "Croûte continentale,Basalte,Gabbro,Dorsale océanique", ""),
("Discontinuité de Mohorovičić", "Limite entre la croûte et le manteau, repérée par un changement brutal de vitesse des ondes sismiques. On l'appelle aussi Moho.", "Croûte continentale,Manteau,Sismologie", ""),
("Gradient géothermique", "Augmentation de la température avec la profondeur, de 25 à 30 °C par kilomètre en moyenne dans la croûte.", "Hydrothermal,Métamorphisme,Magma", ""),
("Plaque lithosphérique", "Grand morceau rigide de lithosphère qui se déplace de quelques centimètres par an. Une quinzaine de plaques recouvrent le globe.", "Tectonique des plaques,Lithosphère,Subduction", ""),
("Dorsale océanique", "Chaîne volcanique sous-marine où deux plaques s'écartent et où naît de la croûte océanique nouvelle.", "Croûte océanique,Tectonique des plaques,Rift", ""),
("Fosse océanique", "Dépression très profonde du fond de l'océan, qui marque l'endroit où une plaque plonge sous une autre.", "Subduction,Plaque lithosphérique,Tectonique des plaques", ""),
("Point chaud", "Remontée localisée de matière très chaude du manteau, qui perce la lithosphère et forme une chaîne de volcans : Hawaï, La Réunion.", "Manteau,Volcanisme,Basalte", ""),
("Rift", "Zone où la croûte continentale se fend et s'étire, formant un fossé bordé de failles. Si elle s'élargit, elle peut donner naissance à un océan.", "Fossé d'effondrement,Graben,Faille", ""),
("Craton", "Partie très ancienne et stable d'un continent, formée de roches de plus de 2 milliards d'années, qui n'a presque pas été déformée depuis.", "Socle,Croûte continentale,Précambrien", ""),
("Socle", "Ensemble de roches anciennes, souvent cristallines et métamorphiques, qui forment la base d'une région et sur lesquelles reposent les roches plus récentes.", "Couverture sédimentaire,Granite,Gneiss", ""),
("Socle hercynien", "Roches du socle formées lors de l'orogenèse hercynienne, il y a plus de 300 millions d'années. On les trouve dans le Massif central, les Vosges, la Bretagne.", "Orogenèse hercynienne,Massif central,Socle", ""),
("Couverture sédimentaire", "Ensemble de couches sédimentaires déposées sur le socle. Elle est épaisse dans les bassins, absente ou mince ailleurs.", "Socle,Bassin sédimentaire,Strate", ""),
("Bassin sédimentaire", "Vaste dépression qui s'est enfoncée lentement et s'est remplie de sédiments sur des millions d'années. Le Bassin parisien et le Bassin aquitain en sont deux exemples.", "Couverture sédimentaire,Sédiment,Roche sédimentaire", ""),
("Fossé d'effondrement", "Zone où le sol s'est affaissé entre deux failles. La Limagne et le fossé rhénan en sont deux exemples.", "Graben,Horst,Faille", ""),
("Horst", "Bloc de la croûte surélevé entre deux failles, par rapport aux blocs voisins qui se sont affaissés.", "Graben,Fossé d'effondrement,Faille", ""),
("Graben", "Bloc de la croûte affaissé entre deux failles, qui forme un fossé. La Limagne est un graben.", "Horst,Fossé d'effondrement,Rift", ""),
("Marge continentale", "Bordure d'un continent qui plonge sous la mer, de la plateforme côtière jusqu'aux grands fonds.", "Croûte continentale,Croûte océanique,Bassin sédimentaire", ""),
("Orogenèse alpine", "Formation des Alpes et des chaînes voisines, par la convergence entre l'Afrique, l'Italie et l'Europe, commencée il y a environ 100 millions d'années, avec des déformations majeures il y a 50 à 20 millions d'années environ.", "Orogenèse,Fente alpine,Subduction", "Quartz"),
("Orogenèse pyrénéenne", "Formation des Pyrénées par la collision entre la plaque ibérique et la plaque européenne, il y a environ 70 à 30 millions d'années.", "Orogenèse,Tectonique des plaques,Chevauchement", ""),
("Massif armoricain", "Ancien massif de roches cristallines et de schistes qui forme la Bretagne, le Cotentin et l'ouest de la Normandie, issu des orogenèses cadomienne et hercynienne.", "Socle hercynien,Orogenèse hercynienne,Granite", ""),
("Massif vosgien", "Massif ancien du nord-est de la France, fait de granites et de gneiss de la chaîne hercynienne, bordé à l'est par le fossé rhénan.", "Socle hercynien,Orogenèse hercynienne,Granite", ""),
("Bassin parisien", "Grand bassin sédimentaire du nord de la France, rempli de couches de calcaire, d'argile et de sable déposées sur plus de 250 millions d'années.", "Bassin sédimentaire,Couverture sédimentaire,Calcaire", ""),
("Bassin aquitain", "Grand bassin sédimentaire du sud-ouest de la France, entre le Massif central et les Pyrénées.", "Bassin sédimentaire,Couverture sédimentaire,Calcaire", ""),
("Chaîne des Puys", "Alignement d'environ quatre-vingts volcans récents en Auvergne, actifs entre 95 000 et 7 000 ans environ, le long de la faille de Limagne. Le puy de Dôme en est le plus connu.", "Volcanisme,Massif central,Faille de Limagne", ""),
("Limagne", "Plaine d'Auvergne installée dans un fossé d'effondrement formé à l'Oligocène, rempli de sédiments, et bordée à l'ouest par la faille de Limagne.", "Fossé d'effondrement,Graben,Oligocène", ""),
("Faille de Limagne", "Grande faille qui borde à l'ouest le fossé de la Limagne en Auvergne. Des filons de baryte s'alignent le long de cette faille.", "Limagne,Faille,Filon", "Baryte"),
("Rift ouest-européen", "Ensemble de fossés d'effondrement formés à l'Oligocène en Europe de l'Ouest, de la Limagne et la Bresse au fossé rhénan.", "Rift,Fossé d'effondrement,Limagne", ""),
# Déformation
("Faille normale", "Faille où un bloc glisse vers le bas par rapport à l'autre, sous l'effet d'un étirement de la croûte.", "Faille,Faille inverse,Graben", ""),
("Faille inverse", "Faille où un bloc est poussé vers le haut par rapport à l'autre, sous l'effet d'une compression de la croûte.", "Faille,Faille normale,Chevauchement", ""),
("Décrochement", "Faille où les deux blocs glissent horizontalement l'un par rapport à l'autre, comme la faille de San Andreas.", "Faille,Faille normale,Faille inverse", ""),
("Chevauchement", "Faille inverse peu inclinée, le long de laquelle un ensemble de roches est poussé sur d'autres.", "Nappe de charriage,Faille inverse,Orogenèse", ""),
("Nappe de charriage", "Grande masse de roches déplacée sur des dizaines de kilomètres par un chevauchement, qui repose sur des terrains plus jeunes.", "Chevauchement,Orogenèse,Pli", ""),
("Discordance", "Surface qui sépare deux ensembles de couches d'orientations différentes : des couches ont été plissées et érodées avant qu'on dépose les autres.", "Strate,Érosion,Stratigraphie", ""),
("Anticlinal", "Pli en forme de voûte, dont les couches les plus anciennes se trouvent au cœur.", "Synclinal,Pli,Strate", ""),
("Synclinal", "Pli en forme de cuvette, dont les couches les plus récentes se trouvent au cœur.", "Anticlinal,Pli,Strate", ""),
("Plissement", "Déformation des couches de roche qui se courbent sans se rompre, sous l'effet d'une compression lente.", "Pli,Anticlinal,Synclinal,Orogenèse", ""),
("Déformation ductile", "Déformation d'une roche qui s'étire ou se plisse sans se rompre, en profondeur où il fait chaud et où la pression est forte.", "Déformation cassante,Pli,Métamorphisme", ""),
("Déformation cassante", "Déformation d'une roche qui se casse en formant des failles ou des diaclases, près de la surface où elle est plus froide.", "Déformation ductile,Faille,Diaclase", ""),
("Fracture", "Cassure d'une roche, avec ou sans déplacement des deux côtés. Elle est appelée faille quand les blocs ont glissé et diaclase quand ils ne bougent pas.", "Faille,Diaclase,Filon", ""),
("Schistosité", "Aptitude d'une roche à se débiter en feuillets, due à l'alignement de minéraux plats comme les micas sous l'effet d'une forte pression.", "Schiste,Foliation,Métamorphisme", ""),
("Foliation", "Structure en feuillets ou en bandes d'une roche métamorphique, due à l'alignement des minéraux. Le gneiss est foliacé.", "Schistosité,Gneiss,Métamorphisme", ""),
("Mylonite", "Roche très finement broyée et étirée le long d'une faille profonde, de grain fin et souvent rubanée.", "Faille,Déformation ductile,Métamorphisme", ""),
("Brèche tectonique", "Brèche formée par le broyage des roches le long d'une faille. Ses fragments anguleux sont ensuite cimentés par des minéraux qui circulent dans la faille.", "Brèche,Faille,Filon", ""),
("Miroir de faille", "Surface lisse, brillante et striée, polie par le frottement des deux blocs le long d'une faille. Elle est souvent couverte d'un film de quartz, de calcite ou de chlorite.", "Faille,Stries,Fracture", "Quartz,Calcite"),
("Séisme", "Secousse du sol provoquée par une rupture brutale le long d'une faille, qui libère de l'énergie sous forme d'ondes.", "Faille,Sismologie,Tectonique des plaques", ""),
# Roches magmatiques et volcaniques
("Intrusion", "Masse de magma qui s'est introduite dans des roches existantes et qui s'y est refroidie lentement, formant une roche à gros grains.", "Pluton,Batholite,Roche plutonique", ""),
("Extrusion", "Montée du magma jusqu'à la surface, où il se répand et se refroidit rapidement pour former des roches volcaniques.", "Lave,Roche volcanique,Intrusion", ""),
("Pluton", "Masse de roche magmatique cristallisée en profondeur, de forme arrondie ou allongée, comme un massif de granite.", "Batholite,Intrusion,Roche plutonique", "Quartz"),
("Batholite", "Très grand massif de roche plutonique, comme le granite, cristallisé en profondeur et qui peut s'étendre sur des centaines de kilomètres.", "Pluton,Granite,Intrusion", ""),
("Dyke", "Lame de roche magmatique qui recoupe les couches ou les roches encaissantes en profondeur. On dit aussi filon.", "Filon,Sill,Intrusion", ""),
("Sill", "Lame de roche magmatique injectée parallèlement aux couches de roche encaissantes, entre deux strates. On dit aussi filon-couche.", "Dyke,Intrusion,Strate", ""),
("Laccolite", "Masse de magma injectée entre des couches qui se bombent au-dessus d'elle, donnant une intrusion en forme de lentille.", "Intrusion,Sill,Pluton", ""),
("Chambre magmatique", "Réservoir de magma situé dans la croûte, sous un volcan ou une intrusion, où le magma s'accumule et cristallise en partie.", "Magma,Volcanisme,Cristallisation fractionnée", ""),
("Cristallisation fractionnée", "Processus au cours duquel les minéraux se forment dans un magma qui refroidit et se séparent du liquide restant, qui change alors de composition.", "Magma,Différenciation magmatique,Chambre magmatique", ""),
("Différenciation magmatique", "Ensemble des processus qui produisent, à partir d'un magma initial, des roches de compositions variées.", "Cristallisation fractionnée,Magma,Roche magmatique", ""),
("Fusion partielle", "Fusion d'une partie seulement d'une roche, des minéraux les plus fusibles, qui donne un magma de composition différente de la roche d'origine.", "Magma,Manteau,Roche magmatique", ""),
("Phénocristal", "Gros cristal visible à l'œil nu dans une roche volcanique ou filonienne à grain fin, formé avant le refroidissement final du magma.", "Texture porphyrique,Porphyre,Microlite", ""),
("Microlite", "Petit cristal aciculaire ou en bâtonnet, visible seulement au microscope, qui forme la pâte de nombreuses roches volcaniques.", "Phénocristal,Texture microlitique,Roche volcanique", ""),
("Texture grenue", "Texture d'une roche formée de cristaux visibles à l'œil nu, serrés les uns contre les autres. Elle caractérise les roches plutoniques comme le granite.", "Roche plutonique,Granite,Texture porphyrique", ""),
("Texture microlitique", "Texture d'une roche volcanique dont la pâte est faite de microlites, avec parfois quelques phénocristaux plus gros.", "Microlite,Roche volcanique,Texture porphyrique", ""),
("Texture porphyrique", "Texture d'une roche qui contient de gros cristaux dans une pâte à grain fin, signe d'un refroidissement en deux temps.", "Porphyre,Phénocristal,Texture grenue", ""),
("Porphyre", "Roche à texture porphyrique : de gros cristaux, comme les feldspaths ou le quartz, noyés dans une pâte à grain fin.", "Texture porphyrique,Phénocristal,Filon", ""),
("Vésicule", "Bulle de gaz figée dans une lave solidifiée, qui laisse une cavité arrondie. La ponce et les scories en sont pleines.", "Amygdale,Lave,Ponce", ""),
("Amygdale", "Vésicule d'une roche volcanique remplie ensuite par des minéraux, comme la calcédoine, le quartz, les zéolites ou la calcite. Les agates se forment souvent ainsi.", "Vésicule,Géode,Zéolite", "Agate,Calcédoine,Quartz"),
("Roche acide", "Roche magmatique riche en silice, à plus de 65 %, claire en général : granite, rhyolite.", "Roche basique,Granite,Silice", ""),
("Roche intermédiaire", "Roche magmatique à teneur moyenne en silice, entre 52 et 65 %, comme la diorite et l'andésite.", "Roche acide,Roche basique,Diorite", ""),
("Roche basique", "Roche magmatique pauvre en silice, de 45 à 52 %, sombre en général, riche en fer et en magnésium : basalte, gabbro.", "Roche acide,Roche ultrabasique,Basalte", ""),
("Roche ultrabasique", "Roche magmatique très pauvre en silice, à moins de 45 %, presque entièrement faite de minéraux sombres : péridotite, dunite.", "Roche basique,Péridotite,Manteau", ""),
("Rhyolite", "Roche volcanique claire, riche en silice, équivalent volcanique du granite, au grain très fin.", "Granite,Roche acide,Roche volcanique", ""),
("Dacite", "Roche volcanique de composition intermédiaire entre l'andésite et la rhyolite, grise à rosée, fréquente dans les volcans de zones de subduction.", "Andésite,Rhyolite,Roche volcanique", ""),
("Andésite", "Roche volcanique grise de composition intermédiaire, typique des volcans de zones de subduction. Son nom vient des Andes.", "Roche intermédiaire,Roche volcanique,Subduction", ""),
("Trachyte", "Roche volcanique claire, riche en feldspath alcalin, à grain fin et au toucher rugueux. Le puy de Dôme est un dôme de trachyte.", "Roche volcanique,Feldspath,Phonolite", ""),
("Phonolite", "Roche volcanique claire, riche en feldspath alcalin et en feldspathoïdes, qui résonne comme une cloche quand on la frappe, d'où son nom.", "Trachyte,Roche volcanique,Feldspath", ""),
("Dolérite", "Roche magmatique sombre, au grain fin à moyen, de même composition que le basalte et le gabbro. On la trouve souvent en filons ou en sills.", "Basalte,Gabbro,Dyke", ""),
("Diorite", "Roche plutonique à grain grossier, de composition intermédiaire, faite surtout de plagioclase et d'amphibole.", "Granite,Gabbro,Roche intermédiaire", ""),
("Granodiorite", "Roche plutonique proche du granite mais plus riche en plagioclase que de feldspath potassique, qui forme une grande part des batholites.", "Granite,Diorite,Batholite", ""),
("Microgranite", "Roche de même composition que le granite mais à grain plus fin, qui s'est refroidie plus rapidement, près de la surface ou en filon.", "Granite,Texture grenue,Porphyre", ""),
("Aplite", "Roche filonienne claire, à grain fin et sucré, de composition proche du granite, souvent associée à la pegmatite.", "Granite,Pegmatite,Filon", ""),
("Obsidienne", "Verre volcanique noir ou brun, issu d'une lave riche en silice refroidie très vite, sans cristaux. Elle se casse en surfaces conchoïdales aux bords coupants.", "Roche volcanique,Cassure conchoïdale,Minéraloïde", ""),
("Ponce", "Roche volcanique très légère et pleine de bulles, qui flotte sur l'eau, faite de verre riche en silice projeté et refroidi brusquement.", "Vésicule,Roche volcanique,Pyroclastite", ""),
("Scorie", "Fragment de lave sombre, rugueux et criblé de bulles, projeté lors d'une éruption. Les cônes de scories de la Chaîne des Puys en sont faits.", "Vésicule,Lave,Chaîne des Puys", ""),
("Téphra", "Ensemble des fragments de roche projetés dans l'air lors d'une éruption : cendres, lapilli, bombes.", "Pyroclastite,Cendre volcanique,Lapilli", ""),
("Pyroclastite", "Roche formée de fragments de lave projetés et déposés par une éruption, comme les tufs et les ignimbrites.", "Téphra,Tuf volcanique,Ignimbrite", ""),
("Cendre volcanique", "Fragments de lave de moins de 2 millimètres projetés par un volcan lors d'une éruption explosive.", "Téphra,Lapilli,Éruption", ""),
("Lapilli", "Petits fragments de lave solidifiée, de 2 à 64 millimètres, projetés lors d'une éruption.", "Téphra,Cendre volcanique,Pyroclastite", ""),
("Bombe volcanique", "Fragment de lave encore pâteuse, de plus de 64 millimètres, projeté et solidifié dans l'air, qui prend souvent une forme en fuseau.", "Téphra,Lapilli,Éruption", ""),
("Tuf volcanique", "Roche formée de cendres volcaniques déposées puis consolidées, tendre et souvent poreuse.", "Pyroclastite,Cendre volcanique,Ignimbrite", ""),
("Ignimbrite", "Roche formée par le dépôt et la soudure de cendres et de fragments chauds d'une coulée pyroclastique.", "Pyroclastite,Coulée pyroclastique,Tuf volcanique", ""),
("Coulée pyroclastique", "Avalanche brûlante de gaz, de cendres et de fragments de roche qui dévale les pentes d'un volcan à grande vitesse.", "Ignimbrite,Éruption,Cendre volcanique", ""),
("Coulée de lave", "Écoulement de lave sur le sol, qui se refroidit et se fige en roche volcanique. Sa forme dépend de la composition de la lave.", "Lave,Volcan,Basalte", ""),
("Volcanisme", "Ensemble des phénomènes liés à la montée du magma jusqu'à la surface : éruptions, coulées, projections de cendres et de gaz.", "Magma,Lave,Volcan", ""),
("Volcan", "Relief formé par l'accumulation de produits d'éruption autour d'une bouche par laquelle le magma remonte.", "Volcanisme,Cratère,Cheminée volcanique", ""),
("Stratovolcan", "Grand volcan conique formé par l'empilement de coulées de lave et de couches de cendres, comme le Vésuve ou le Fuji.", "Volcan,Pyroclastite,Éruption", ""),
("Volcan bouclier", "Volcan très large aux pentes douces, formé de coulées de lave très fluides, comme ceux d'Hawaï ou le piton de la Fournaise.", "Volcan,Basalte,Point chaud", ""),
("Cheminée volcanique", "Conduit par lequel le magma, les gaz et les cendres remontent jusqu'à la bouche d'un volcan.", "Volcan,Cratère,Chambre magmatique", ""),
("Cratère", "Dépression en forme d'entonnoir, au sommet ou sur les flancs d'un volcan, par laquelle sortent les produits d'éruption.", "Volcan,Cheminée volcanique,Caldeira", ""),
("Caldeira", "Vaste dépression circulaire formée par l'effondrement d'un volcan vidé de son magma, bien plus large qu'un cratère.", "Cratère,Volcan,Chambre magmatique", ""),
("Maar", "Cratère large et peu profond, souvent occupé par un lac, creusé par une explosion due au contact entre magma et eau souterraine.", "Cratère,Volcan,Éruption", ""),
("Dôme volcanique", "Relief bombé formé par une lave très visqueuse qui s'accumule au-dessus de la bouche sans pouvoir s'écouler. Le puy de Dôme en est un.", "Trachyte,Lave,Chaîne des Puys", ""),
("Éruption", "Sortie de lave, de gaz et de fragments de roche par un volcan. Elle est dite effusive quand la lave coule et explosive quand elle est projetée.", "Volcan,Lave,Téphra", ""),
("Solfatare", "Émission de gaz soufrés chauds par un volcan peu actif, qui dépose du soufre et des sulfates sur les roches.", "Fumerolle,Volcanisme,Sulfure", "Soufre"),
("Geyser", "Source d'eau chaude qui jaillit par intermittence, chauffée par une roche volcanique en profondeur.", "Source thermale,Hydrothermal,Volcanisme", ""),
("Source thermale", "Source dont l'eau sort plus chaude que l'air ambiant, réchauffée en profondeur par la chaleur de la Terre. Elle dépose souvent des minéraux.", "Hydrothermal,Source minérale,Travertin", ""),
("Source minérale", "Source dont l'eau est chargée en sels minéraux dissous, comme le calcium, le magnésium ou le sodium.", "Source thermale,Dissolution,Hydrothermal", ""),
("Fumeur noir", "Cheminée hydrothermale sous-marine qui rejette de l'eau très chaude et noire, chargée de sulfures de fer, de cuivre et de zinc, qui précipitent en se refroidissant.", "Hydrothermal,Dorsale océanique,Sulfure", "Pyrite,Chalcopyrite,Sphalérite"),
("Fluide hydrothermal", "Eau chaude, riche en éléments dissous, qui circule dans les fractures de la croûte et qui dépose des minéraux dans les filons.", "Hydrothermal,Filon,Altération hydrothermale", ""),
("Altération hydrothermale", "Transformation d'une roche par un fluide chaud qui la traverse. Elle change ses minéraux et dépose des minéraux nouveaux.", "Hydrothermal,Fluide hydrothermal,Métasomatisme", ""),
("Silicification", "Remplacement ou enrobage d'une roche, d'un fossile ou d'un bois par de la silice. Elle donne le bois pétrifié et certaines brèches.", "Silice,Pétrification,Bois pétrifié", "Quartz,Calcédoine"),
# Roches sédimentaires et processus
("Sédiment", "Matière détachée d'une roche par l'érosion, transportée puis déposée par l'eau, le vent ou la glace : sable, argile, galets, boue.", "Sédimentation,Roche sédimentaire,Érosion", ""),
("Sédimentation", "Dépôt de sédiments, couche après couche, par l'eau, le vent ou la glace, ou par précipitation et accumulation de matière.", "Sédiment,Strate,Diagenèse", ""),
("Compaction", "Tassement des sédiments sous le poids des couches qui s'empilent au-dessus d'eux, qui chasse l'eau et réduit le volume.", "Diagenèse,Lithification,Sédiment", ""),
("Cimentation", "Dépôt de minéraux entre les grains d'un sédiment, qui les soude et le transforme en roche. Le calcaire, la silice et l'oxyde de fer sont des ciments courants.", "Lithification,Diagenèse,Grès", ""),
("Lithification", "Transformation d'un sédiment meuble en roche dure, par compaction et cimentation.", "Compaction,Cimentation,Diagenèse", ""),
("Précipitation", "Dépôt d'une substance solide à partir d'une solution devenue trop concentrée ou dont les conditions ont changé. Elle forme beaucoup de minéraux.", "Dissolution,Cristallisation,Évaporite", ""),
("Dissolution", "Passage d'un minéral en solution dans l'eau. Elle creuse le calcaire, les gypses et le sel, et alimente la formation de nouveaux minéraux ailleurs.", "Précipitation,Karst,Solubilité", ""),
("Recristallisation", "Transformation d'un minéral en cristaux plus gros ou mieux formés, sous l'effet de la chaleur, de la pression ou d'un fluide, sans changer de composition.", "Métamorphisme,Cristallisation,Marbre", ""),
("Lessivage", "Entraînement d'éléments dissous par l'eau qui traverse une roche ou un sol, qui s'appauvrit en certains éléments et s'enrichit en d'autres.", "Dissolution,Latérite,Altération", ""),
("Stratification", "Disposition en couches parallèles des roches sédimentaires, qui correspond aux dépôts successifs.", "Strate,Sédimentation,Stratigraphie", ""),
("Strate", "Couche de roche sédimentaire déposée en une seule fois, délimitée par deux surfaces. On dit aussi banc ou couche.", "Stratification,Stratigraphie,Roche sédimentaire", ""),
("Banc", "Couche épaisse et homogène de roche sédimentaire, séparée de la suivante par un joint.", "Strate,Stratification,Calcaire", ""),
("Brèche", "Roche formée de fragments anguleux cimentés ensemble, dont l'angularité montre qu'ils n'ont pas beaucoup voyagé.", "Conglomérat,Brèche tectonique,Roche sédimentaire", ""),
("Conglomérat", "Roche formée de galets arrondis cimentés, dont la forme indique qu'ils ont été roulés par l'eau.", "Brèche,Galet,Roche sédimentaire", ""),
("Arkose", "Grès riche en feldspath, issu de la destruction rapide d'un granite. Sa couleur est souvent rosée ou ocre.", "Grès,Feldspath,Granite", "Feldspath"),
("Grauwacke", "Grès sombre, mal trié, riche en fragments de roches et en argile, déposé rapidement en mer profonde.", "Grès,Roche sédimentaire,Argile", ""),
("Argilite", "Roche sédimentaire à grain très fin, formée d'argile consolidée, qui ne se délite pas en feuillets.", "Argile,Roche sédimentaire,Schiste", ""),
("Marne", "Roche sédimentaire faite d'un mélange d'argile et de calcaire, tendre et souvent grise ou beige.", "Calcaire,Argile,Roche sédimentaire", ""),
("Dolomie", "Roche carbonatée faite surtout du minéral dolomite, de composition proche du calcaire mais plus riche en magnésium.", "Calcaire,Carbonate,Roche carbonatée", "Dolomite"),
("Craie", "Calcaire blanc, tendre et poreux, formé de coquilles microscopiques d'algues marines déposées au Crétacé.", "Calcaire,Silex,Crétacé", "Calcite"),
("Roche carbonatée", "Roche sédimentaire formée de plus de la moitié de carbonates : calcaire, craie, dolomie.", "Calcaire,Dolomie,Carbonate", "Calcite,Dolomite"),
("Roche détritique", "Roche sédimentaire formée de fragments d'autres roches, comme le grès, le conglomérat ou l'argilite.", "Sédiment,Grès,Conglomérat", ""),
("Sable", "Ensemble de grains de roche ou de minéral de 0,06 à 2 millimètres, le plus souvent du quartz.", "Sédiment,Grès,Alluvion", "Quartz"),
("Galet", "Fragment de roche arrondi par le transport dans l'eau, de 2 à 25 centimètres environ.", "Conglomérat,Alluvion,Sédiment", ""),
("Houille", "Charbon noir et dur, formé par la transformation de végétaux accumulés dans des marécages il y a plus de 300 millions d'années.", "Charbon,Lignite,Carbonifère", ""),
("Charbon", "Roche sédimentaire combustible, formée par la transformation de débris de végétaux enfouis. Elle va de la tourbe à l'anthracite.", "Houille,Lignite,Tourbe", ""),
("Lignite", "Charbon brun, jeune et peu dur, issu de végétaux enfouis depuis quelques dizaines de millions d'années.", "Charbon,Houille,Tourbe", ""),
("Tourbe", "Matière brune formée de végétaux partiellement décomposés dans des marais, premier stade de la formation du charbon.", "Charbon,Lignite,Houille", ""),
("Oolithe", "Petite sphère de carbonate, de la taille d'un grain de sable, formée par dépôt de couches concentriques autour d'un noyau dans une eau agitée.", "Oolithique,Calcaire,Concrétion", "Calcite,Aragonite"),
("Pisolithe", "Concrétion sphérique de la taille d'un pois, faite de couches concentriques de carbonate de calcium, que l'on trouve dans les grottes et les sources.", "Pisolitique,Oolithe,Concrétion", "Calcite"),
("Septaria", "Gros nodule d'argile ou de marne, fendu en polygones et dont les fentes sont remplies de calcite.", "Nodule,Concrétion,Calcite", "Calcite"),
("Sel gemme", "Roche faite de halite, déposée par l'évaporation d'anciennes mers ou lagunes.", "Évaporite,Halite,Sulfate", "Halite"),
("Travertin", "Roche calcaire déposée par des sources chargées en carbonate, souvent poreuse et finement litée. Elle se forme encore aux sources thermales.", "Source thermale,Calcaire,Spéléothème", "Calcite,Aragonite"),
("Loess", "Dépôt de poussières très fines, jaunâtres, apportées par le vent pendant les périodes glaciaires. Il forme des sols très fertiles.", "Sédiment,Quaternaire,Moraine", ""),
("Moraine", "Amas de blocs, de graviers et de sable déposés par un glacier, qui garde la forme du glacier qui l'a laissé.", "Sédiment,Quaternaire,Érosion", ""),
("Terrasse alluviale", "Replat dans une vallée, formé par d'anciennes alluvions déposées par une rivière qui s'est ensuite enfoncée.", "Alluvion,Galet,Placer", ""),
("Éluvion", "Matériaux altérés qui sont restés sur place, au-dessus de la roche dont ils proviennent. Ils peuvent concentrer des minéraux résistants.", "Colluvion,Alluvion,Altération", ""),
("Colluvion", "Matériaux déplacés par la gravité, la pluie ou le ruissellement sur un versant, et accumulés en bas de pente.", "Éluvion,Alluvion,Érosion", ""),
("Doline", "Dépression fermée, en forme de cuvette ou d'entonnoir, due à la dissolution du calcaire ou à l'effondrement d'une cavité.", "Karst,Dissolution,Spéléothème", ""),
("Grotte", "Cavité naturelle souterraine, creusée surtout dans le calcaire par la dissolution due à l'eau.", "Karst,Spéléothème,Stalactite", ""),
("Spéléothème", "Toute concrétion formée dans une grotte : stalactite, stalagmite, draperie, colonne ou excentrique.", "Stalactite,Stalagmite,Grotte,Concrétion", "Calcite,Aragonite"),
# Roches métamorphiques
("Faciès métamorphique", "Ensemble de roches métamorphiques formées dans les mêmes conditions de pression et de température, qui contiennent donc les mêmes minéraux caractéristiques.", "Métamorphisme,Minéral index,Schiste bleu", ""),
("Minéral index", "Minéral dont la présence indique des conditions de température et de pression précises dans une roche métamorphique, comme la chlorite, le grenat, la staurotide ou la sillimanite.", "Isograde,Faciès métamorphique,Métamorphisme", "Grenat,Staurotide"),
("Isograde", "Ligne qui, sur une carte, joint les points où apparaît le même minéral index dans les roches métamorphiques.", "Minéral index,Faciès métamorphique,Métamorphisme", ""),
("Amphibolite", "Roche métamorphique sombre, faite surtout d'amphibole et de plagioclase, issue de basalte ou de gabbro transformé.", "Métamorphisme,Amphibole,Roche métamorphique", ""),
("Cornéenne", "Roche très dure, à grain fin, formée autour d'une intrusion par la chaleur qui transforme les roches voisines.", "Métamorphisme de contact,Auréole de contact,Roche métamorphique", ""),
("Migmatite", "Roche formée d'un mélange de roche métamorphique et de roche issue de sa fusion partielle, qui donne des bandes claires et sombres.", "Anatexie,Gneiss,Granite", ""),
("Anatexie", "Fusion partielle de roches de la croûte à haute température, qui produit un magma granitique et des migmatites.", "Migmatite,Fusion partielle,Granite", ""),
("Granulite", "Roche métamorphique de haute température, claire et à grain fin, formée à grande profondeur dans la croûte continentale.", "Gneiss,Métamorphisme,Roche métamorphique", ""),
("Protolithe", "Roche d'origine avant qu'elle soit transformée par le métamorphisme. Le calcaire est le protolithe du marbre.", "Métamorphisme,Marbre,Roche métamorphique", ""),
("Auréole de contact", "Zone autour d'une intrusion où les roches voisines ont été transformées par la chaleur du magma. Elle peut être riche en minéraux de skarn ou en cornéennes.", "Métamorphisme de contact,Cornéenne,Skarn", ""),
("Roche encaissante", "Roche qui entoure et contient un filon, une intrusion ou un gisement.", "Filon,Intrusion,Éponte", ""),
("Roche mère", "Roche dont dérivent un sol, un sédiment ou une autre roche. Elle peut aussi désigner celle où se forme le pétrole.", "Protolithe,Altération,Sédiment", ""),
# Gisements et mine
("Veine", "Mince filon de minéraux qui remplit une fracture dans une roche. On parle de veines de quartz, de calcite ou de minerai.", "Filon,Fracture,Stockwerk", "Quartz,Calcite"),
("Stockwerk", "Réseau dense de petits filons entrecroisés dans une roche, qui forme une masse minéralisée.", "Veine,Filon,Gisement", ""),
("Éponte", "Paroi d'un filon, au contact de la roche encaissante. On distingue l'éponte supérieure, ou toit, et l'éponte inférieure, ou mur.", "Filon,Roche encaissante,Salbande", ""),
("Salbande", "Bande de roche altérée ou de minéraux argileux le long de la paroi d'un filon, entre le filon et la roche encaissante.", "Éponte,Filon,Roche encaissante", ""),
("Pendage", "Inclinaison d'une couche, d'une faille ou d'un filon par rapport à l'horizontale, mesurée en degrés.", "Strate,Filon,Faille", ""),
("Teneur", "Proportion de métal ou de substance utile dans un minerai, exprimée en pourcentage ou en grammes par tonne.", "Minerai,Gisement,Gangue", ""),
("Stérile", "Roche sans valeur extraite d'une mine en même temps que le minerai, qui est mise en haldes.", "Gangue,Halde,Minerai", ""),
("Descenderie", "Galerie inclinée qui descend vers les travaux d'une mine, en pente moins raide qu'un puits.", "Galerie,Puits,Mine", ""),
("Front de taille", "Surface de roche en cours d'exploitation dans une mine ou une carrière, d'où l'on abat le minerai ou la pierre.", "Mine,Carrière,Galerie", ""),
("Boisage", "Soutènement en bois qui retient les parois et le plafond d'une galerie de mine pour éviter les éboulements.", "Galerie,Mine,Puits", ""),
("Mine à ciel ouvert", "Exploitation en carrière géante, où l'on enlève les roches de surface pour atteindre le minerai en gradins.", "Mine,Carrière,Mine souterraine", ""),
("Mine souterraine", "Exploitation par puits et galeries qui suit le minerai en profondeur.", "Mine,Galerie,Puits", ""),
("Ardoisière", "Exploitation d'ardoise, roche métamorphique qui se débite en minces plaques grâce à sa schistosité.", "Schistosité,Carrière,Schiste", ""),
("Exploration minière", "Ensemble des travaux de recherche d'un gisement : cartes, mesures, prélèvements, sondages.", "Prospection,Sondage,Gisement", ""),
("Concession minière", "Droit d'exploiter les minéraux d'un secteur, accordé par l'État. En France, les mines relèvent du code minier.", "Mine,Gisement,Prospection", ""),
("Orpaillage", "Recherche de l'or dans les alluvions par lavage à la batée, à la sluice ou à l'aide d'autres outils.", "Placer,Batée,Pépite", "Or"),
("Gisement filonien", "Gisement formé de minéraux déposés dans des fractures par des fluides chauds, sous forme de filons.", "Filon,Gisement,Hydrothermal", ""),
("Gisement alluvionnaire", "Gisement de minéraux denses ou précieux concentrés par une rivière : or, étain, diamant, gemmes.", "Placer,Alluvion,Orpaillage", "Or,Cassitérite"),
("Gisement stratiforme", "Gisement de minerai disposé en couche, parallèlement aux strates de la roche qui l'encaisse.", "Strate,Minerai,Gisement", ""),
("Gisement magmatique", "Gisement formé par la cristallisation d'un magma, qui concentre certains minéraux utiles : chromite, platine, diamant dans les kimberlites.", "Magma,Kimberlite,Gisement", "Chromite"),
("Gisement hydrothermal", "Gisement formé par le dépôt de minéraux issus de fluides chauds qui circulent dans la croûte.", "Hydrothermal,Fluide hydrothermal,Filon", ""),
("Laverie", "Installation où l'on lave et trie le minerai broyé pour en séparer les minéraux utiles de la gangue.", "Minerai,Gangue,Mine", ""),
("Patrimoine minier", "Ensemble des traces laissées par l'activité minière passée : galeries, bâtiments, haldes, outils, archives, paysages et savoir-faire.", "Mine,Halde,Galerie", ""),
# Météorites et impacts
("Météorite", "Roche ou métal venu de l'espace et tombé sur Terre. On les range en météorites pierreuses, ferreuses et mixtes.", "Chondrite,Achondrite,Pallasite", ""),
("Chondrite", "Météorite pierreuse contenant de petites sphères, les chondres. Elle fait partie des matières les plus anciennes du système solaire, âgée d'environ 4,5 milliards d'années.", "Météorite,Achondrite,Datation", ""),
("Achondrite", "Météorite pierreuse sans chondres, issue d'un astre qui a fondu et s'est différencié, comme les météorites de la Lune ou de Mars.", "Météorite,Chondrite,Pallasite", ""),
("Pallasite", "Météorite mixte de fer-nickel dans lequel sont enchâssés des cristaux d'olivine verts, parfois de qualité gemme.", "Météorite,Olivine,Gemme", "Olivine"),
("Tectite", "Petit verre naturel, formé par la fusion de roches terrestres lors de l'impact d'une météorite et projeté à grande distance. La moldavite en est une.", "Impactite,Minéraloïde,Météorite", ""),
("Impactite", "Roche transformée par le choc d'une météorite : roche fondue, brèche d'impact ou roche aux minéraux déformés.", "Cratère d'impact,Tectite,Brèche", ""),
("Cratère d'impact", "Dépression creusée par la chute d'une météorite. En France, celui de Rochechouart (Charente) est l'un des plus grands d'Europe.", "Impactite,Météorite,Astroblème", ""),
("Astroblème", "Structure circulaire très ancienne, usée par l'érosion, qui marque la place d'un cratère d'impact.", "Cratère d'impact,Impactite,Météorite", ""),
("Fulgurite", "Tube de verre formé quand la foudre frappe le sable ou la roche et la fait fondre sur son passage.", "Minéraloïde,Silice,Quartz", ""),
# Fossiles
("Fossilisation", "Ensemble des processus qui conservent un être vivant, ou la trace de sa vie, dans une roche.", "Fossile,Pétrification,Empreinte", ""),
("Pétrification", "Transformation d'un organisme en pierre : ses tissus sont remplacés par des minéraux, comme le quartz ou la calcite, qui gardent sa forme.", "Fossilisation,Silicification,Bois pétrifié", "Quartz,Calcite"),
("Bois pétrifié", "Bois fossile dont les cellules ont été remplacées par de la silice, de l'opale ou de la calcédoine, qui conservent souvent les cernes de l'arbre.", "Pétrification,Silicification,Fossile", "Quartz,Opale,Calcédoine"),
("Empreinte", "Trace en creux ou en relief d'un organisme, d'une feuille ou d'un pas, conservée dans une roche sédimentaire.", "Fossile,Fossilisation,Roche sédimentaire", ""),
("Ammonite", "Mollusque marin fossile à coquille enroulée en spirale, éteint à la fin du Crétacé. Elle sert de fossile stratigraphique.", "Fossile,Fossile stratigraphique,Mésozoïque", ""),
("Trilobite", "Arthropode marin fossile du Paléozoïque, au corps divisé en trois lobes, éteint il y a environ 250 millions d'années.", "Fossile,Paléozoïque,Fossile stratigraphique", ""),
("Bélemnite", "Fossile en forme de balle, partie solide du squelette d'un mollusque marin voisin de la seiche, éteint à la fin du Crétacé.", "Fossile,Mésozoïque,Crétacé", ""),
("Fossile stratigraphique", "Fossile d'une espèce qui a vécu peu de temps mais sur une grande surface, et qui permet de dater la couche de roche dans laquelle on le trouve.", "Stratigraphie,Fossile,Datation", ""),
# Datation et temps
("Datation radiométrique", "Méthode qui mesure l'âge d'une roche ou d'un minéral grâce à la désintégration régulière d'éléments radioactifs qu'il contient.", "Demi-vie,Datation,Isotope", "Zircon"),
("Demi-vie", "Temps nécessaire pour que la moitié des atomes d'un élément radioactif se désintègre. Elle sert de chronomètre pour dater les roches.", "Datation radiométrique,Radioactivité,Isotope", ""),
("Isotope", "Variante d'un élément chimique dont le noyau compte un nombre différent de neutrons. Certains sont radioactifs et servent à dater les roches.", "Datation radiométrique,Élément chimique,Demi-vie", ""),
("Précambrien", "Temps géologique qui précède le Cambrien : de la formation de la Terre, il y a 4,5 milliards d'années, à environ 539 millions d'années. Il couvre près de 90 % de l'histoire de la Terre.", "Échelle des temps géologiques,Archéen,Protérozoïque", ""),
("Archéen", "Éon géologique qui s'étend d'environ 4 à 2,5 milliards d'années. Les plus vieux continents et les premières traces de vie datent de cette époque.", "Précambrien,Craton,Échelle des temps géologiques", ""),
("Protérozoïque", "Éon géologique compris entre 2,5 milliards d'années et 539 millions d'années, marqué par l'apparition de l'oxygène dans l'atmosphère et des premiers êtres pluricellulaires.", "Précambrien,Archéen,Échelle des temps géologiques", ""),
("Paléozoïque", "Ère géologique de 539 à 252 millions d'années, de l'explosion de la vie au Cambrien jusqu'à la grande extinction du Permien. L'orogenèse hercynienne s'y déroule.", "Échelle des temps géologiques,Cambrien,Permien", ""),
("Mésozoïque", "Ère géologique de 252 à 66 millions d'années, qui comprend le Trias, le Jurassique et le Crétacé, l'âge des dinosaures.", "Échelle des temps géologiques,Trias,Crétacé", ""),
("Cénozoïque", "Ère géologique qui commence il y a 66 millions d'années, après la disparition des dinosaures, et qui se poursuit aujourd'hui. Elle comprend le Paléogène, le Néogène et le Quaternaire.", "Échelle des temps géologiques,Paléogène,Quaternaire", ""),
("Cambrien", "Première période du Paléozoïque, de 539 à 485 millions d'années, marquée par l'apparition de la plupart des grands groupes d'animaux.", "Paléozoïque,Échelle des temps géologiques,Trilobite", ""),
("Ordovicien", "Période géologique de 485 à 444 millions d'années, marquée par un essor de la vie marine et par une glaciation à la fin.", "Paléozoïque,Silurien,Échelle des temps géologiques", ""),
("Silurien", "Période géologique de 444 à 419 millions d'années, durant laquelle les premières plantes colonisent les terres.", "Paléozoïque,Ordovicien,Dévonien", ""),
("Dévonien", "Période géologique de 419 à 359 millions d'années, souvent appelée âge des poissons, qui voit apparaître les premières forêts.", "Paléozoïque,Silurien,Carbonifère", ""),
("Carbonifère", "Période géologique de 359 à 299 millions d'années, au cours de laquelle de vastes forêts donnent les grands gisements de houille.", "Paléozoïque,Houille,Orogenèse hercynienne", ""),
("Permien", "Dernière période du Paléozoïque, de 299 à 252 millions d'années, qui se termine par la plus grande extinction de masse connue.", "Paléozoïque,Carbonifère,Trias", ""),
("Trias", "Première période du Mésozoïque, de 252 à 201 millions d'années, qui voit apparaître les premiers dinosaures et les premiers mammifères.", "Mésozoïque,Permien,Jurassique", ""),
("Jurassique", "Période géologique de 201 à 145 millions d'années, qui tire son nom du Jura. Les dinosaures y dominent, et l'océan Atlantique commence à s'ouvrir.", "Mésozoïque,Trias,Crétacé", ""),
("Crétacé", "Dernière période du Mésozoïque, de 145 à 66 millions d'années, qui tire son nom de la craie, et qui se termine par la disparition des dinosaures.", "Mésozoïque,Craie,Jurassique", ""),
("Paléogène", "Première période du Cénozoïque, de 66 à 23 millions d'années, qui comprend le Paléocène, l'Éocène et l'Oligocène.", "Cénozoïque,Oligocène,Néogène", ""),
("Oligocène", "Dernière époque du Paléogène, de 34 à 23 millions d'années. C'est à cette époque que se creusent la Limagne et les fossés de l'ouest de l'Europe.", "Paléogène,Limagne,Rift ouest-européen", ""),
("Néogène", "Période géologique de 23 à 2,6 millions d'années, qui comprend le Miocène et le Pliocène.", "Cénozoïque,Paléogène,Quaternaire", ""),
("Quaternaire", "Période géologique qui commence il y a 2,6 millions d'années et se poursuit aujourd'hui, marquée par les glaciations et par l'apparition de l'espèce humaine.", "Cénozoïque,Moraine,Loess", ""),
]
